name: CI

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:

  app-setup:
    uses: favedom-dev/github-reusable-workflow/.github/workflows/app-setup.yaml@master

  repo-version:
    uses: favedom-dev/github-reusable-workflow/.github/workflows/repo-version.yaml@master
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  maven-docker:
    uses: favedom-dev/github-reusable-workflow/.github/workflows/maven-docker.yaml@master
    needs: [app-setup, repo-version]
    with:
      NAME: ${{ needs.app-setup.outputs.NAME }}
      VERSION: ${{ needs.repo-version.outputs.version }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      WIF_PROVIDER: '${{ secrets.WIF_PROVIDER }}'
      WIF_SERVICE_ACCOUNT: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

  helm-charts:
    uses: favedom-dev/github-reusable-workflow/.github/workflows/helm-charts.yaml@master
    needs: [app-setup, repo-version, maven-docker]
    with:
      NAME: ${{ needs.app-setup.outputs.NAME }}
      VERSION: ${{ needs.repo-version.outputs.version }}
      PREVIEW_NAMESPACE: ${{ needs.app-setup.outputs.PREVIEW_NAMESPACE }}
      API_PATH: ${{ needs.app-setup.outputs.API_PATH }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      WIF_PROVIDER: '${{ secrets.WIF_PROVIDER }}'
      WIF_SERVICE_ACCOUNT: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

  stackhawk:
    uses: favedom-dev/github-reusable-workflow/.github/workflows/stackhawk.yaml@master
    needs: [app-setup, repo-version, maven-docker, helm-charts]
    if: github.event_name == 'pull_request' && needs.app-setup.outputs.IS_STACKHAWK_READY == 'true'
    with:
      NAME: ${{ needs.app-setup.outputs.NAME }}
      NAMESPACE: ${{ needs.app-setup.outputs.PREVIEW_NAMESPACE }}
      API_PATH: ${{ needs.app-setup.outputs.API_PATH }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      HAWK_API_KEY: ${{ secrets.HAWK_API_KEY }}
      TEST_PASSWORD: ${{ secrets.STACKHAWK_USER_PASSWORD }}

  staging:
    uses: favedom-dev/github-reusable-workflow/.github/workflows/argocd-deploy-env.yaml@master
    needs: [app-setup, repo-version, maven-docker, helm-charts]
    if: github.ref == 'refs/heads/master'
    with:
      NAME: ${{ needs.app-setup.outputs.NAME }}
      VERSION: ${{ needs.repo-version.outputs.version }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
