name: "Set PR Version"
description: "Sets version and build-version for pull requests"

inputs:
  event-name:
    description: "GitHub event name (e.g., pull_request)"
    required: true
  pr-number:
    description: "Pull request number (github.event.number)"
    required: true
  run-number:
    description: "Workflow run number (github.run_number)"
    required: true
  run-attempt:
    description: "Workflow run attempt (github.run_attempt)"
    required: true

outputs:
  version:
    description: "PR version string"
    value: ${{ steps.set-pr-version.outputs.version }}
  build-version:
    description: "PR build version string"
    value: ${{ steps.set-pr-version.outputs.build-version }}

runs:
  using: "composite"
  steps:
    - name: "Set PR Version"
      id: set-pr-version
      # if: ${{ inputs.event-name == 'pull_request' }}
      run: |
        # pr_number="${{ inputs.pr-number }}"
        echo "github.ref_name : ${{ github.ref_name }}"
        pr_number=$(gh pr view ${{ github.ref_name }} --json number --jq '.number' || echo "")
        echo "pr_number=$PR" >> $GITHUB_OUTPUT
        pr_run_number="${{ inputs.run-number }}"
        pr_run_attempt="${{ inputs.run-attempt }}"
        build_version="${{ inputs.pr-number }}.${{ inputs.run-number }}.${{ inputs.run-attempt }}"

        echo "PR Number        (github.event.number) : ${{ inputs.pr-number }}"
        echo "PR Run Number    (github.run_number)   : ${{ inputs.run-number }}"
        echo "PR Run Attempt   (github.run_attempt)  : ${{ inputs.run-attempt }}"
        echo "PR Build Version                       : ${build_version}"
        echo "build-version=${build_version}" >> $GITHUB_OUTPUT
        echo "version=0.0.0-SNAPSHOT-PR-${{ inputs.pr-number }}-${{ inputs.run-number }}-${{ inputs.run-attempt }}" >> $GITHUB_OUTPUT
      shell: bash
