name: Flyway Docker Build

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    # paths:
    #   - '${APP_NAME}/**'
    #   - 'docker/**'
    #   - '**/Dockerfile'

jobs:

  set-app-name:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    uses: favedom-dev/github-reusable-workflow/.github/workflows/set-app-name.yaml@master

  lint-sql:
    uses: favedom-dev/github-reusable-workflow/.github/workflows/lint-sql.yaml@master
    if: github.event_name == 'pull_request'
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  repo-version:
    uses: favedom-dev/github-reusable-workflow/.github/workflows/repo-version.yaml@master
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  docker:
    uses: favedom-dev/github-reusable-workflow/.github/workflows/flyway-docker-build.yaml@master
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    needs: [set-app-name, repo-version]
    with:
      NAME: ${{ needs.set-app-name.outputs.NAME }}
      VERSION: ${{ needs.repo-version.outputs.version }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      WIF_PROVIDER: '${{ secrets.WIF_PROVIDER }}'
      WIF_SERVICE_ACCOUNT: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

  staging:
    uses: favedom-dev/github-reusable-workflow/.github/workflows/deploy-env.yaml@master
    needs: [set-app-name, docker]
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    with:
      NAME: ${{ needs.set-app-name.outputs.NAME }}
      VERSION: ${{ needs.repo-version.outputs.version }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
