name: CI

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:

  app-setup:
    uses: favedom-dev/github-reusable-workflow/.github/workflows/app-setup.yaml@master

  repo-version:
    uses: favedom-dev/github-reusable-workflow/.github/workflows/repo-version.yaml@master
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  maven-docker:
    uses: favedom-dev/github-reusable-workflow/.github/workflows/maven-docker.yaml@master
    needs: [app-setup, repo-version]
    with:
      NAME: ${{ needs.app-setup.outputs.NAME }}
      VERSION: ${{ needs.repo-version.outputs.version }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      WIF_PROVIDER: '${{ secrets.WIF_PROVIDER }}'
      WIF_SERVICE_ACCOUNT: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

  helm-charts:
    uses: favedom-dev/github-reusable-workflow/.github/workflows/helm-charts.yaml@master
    needs: [app-setup, repo-version, maven-docker]
    with:
      NAME: ${{ needs.app-setup.outputs.NAME }}
      VERSION: ${{ needs.repo-version.outputs.version }}
      PREVIEW_NAMESPACE: ${{ needs.app-setup.outputs.PREVIEW_NAMESPACE }}
      API_PATH: ${{ needs.app-setup.outputs.API_PATH }}
      # HELM_ADD_REPOS: true
      # BPM Skipping preview for 2 reasons:
      # 1) not used, including stackhawk
      # 2) helm upgrade error
      #    requires one of ["container.roles.create"] permission(s).
      #    Error: UPGRADE FAILED: failed to create resource: roles.rbac.authorization.k8s.io is forbidden:
      #    User "***" cannot create resource "roles" in API group "rbac.authorization.k8s.io" in the namespace
      #    "pr-peeq-shoutout-bpm-70": No policy matched.
      DO_PREVIEW_ENVIRONMENT: false
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      WIF_PROVIDER: '${{ secrets.WIF_PROVIDER }}'
      WIF_SERVICE_ACCOUNT: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

  staging:
    uses: favedom-dev/github-reusable-workflow/.github/workflows/argocd-deploy-env.yaml@master
    needs: [app-setup, repo-version, maven-docker, helm-charts]
    if: github.ref == 'refs/heads/master'
    with:
      NAME: ${{ needs.app-setup.outputs.NAME }}
      VERSION: ${{ needs.repo-version.outputs.version }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
