name: Recovering secrets

# Assumption:
# You've created the following GitHub secrets in your repository:
# MY_SECRET - encode/decode with base64 - useful for private repositories

on:
  push:
  workflow_dispatch:

jobs:
  base64:
    name: Recover With Base64
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          echo "MY_SECRET (***)    = ${MY_SECRET}"
          echo "MY_SECRET (base64) = $(echo ${MY_SECRET} | base64)"
          echo "Copy the above value, and then execute locally:"
          echo "echo PASTE_HERE | base64 -D"
