name: "Setup Trivy"
description: "Setup security values"

inputs:
  do-trivy:
    description: "Force Trivy run"
    required: false

outputs:
  DO_TRIVY:
    description: "Whether to run trivy"
    value: ${{ steps.trivy-scan-prep.outputs.DO_TRIVY }}

runs:
  using: "composite"
  steps:
    - name: "Trivy scan prep"
      id: trivy-scan-prep
      shell: bash
      env:
        DO_TRIVY: ${{ inputs.do-trivy }}
      run: |
        if [[ ${DO_TRIVY} == "true" ]]; then
          DO_TRIVY=true
        else
          if [ "${{ github.event_name }}" != "pull_request" ]; then
            DO_TRIVY=false
          else
            DO_TRIVY=true
          fi
        fi
        echo "DO_TRIVY : ${DO_TRIVY}"
        echo "DO_TRIVY=${DO_TRIVY}" >> $DO_TRIVY