name: Preview cleanup

on:  # yamllint disable-line rule:truthy
  pull_request:
    types:
      - closed

jobs:

  app-setup:
    uses: favedom-dev/github-reusable-workflow/.github/workflows/app-setup.yaml@master

  preview-cleanup:
    uses: favedom-dev/github-reusable-workflow/.github/workflows/preview-env-cleanup.yaml@master
    needs: [app-setup]
    with:
      NAME: ${{ needs.app-setup.outputs.NAME }}
      PREVIEW_NAMESPACE: ${{ needs.app-setup.outputs.PREVIEW_NAMESPACE }}
    secrets:
      WIF_PROVIDER: '${{ secrets.WIF_PROVIDER }}'
      WIF_SERVICE_ACCOUNT: '${{ secrets.WIF_SERVICE_ACCOUNT }}'
