name: App Setup

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      OVERRIDE_NAME:
        required: false
        type: string

      OVERRIDE_PREVIEW_NAMESPACE:
        required: false
        type: string

      USE_REPO_NAME_PREVIEW_NAMESPACE:
        default: false
        required: false
        type: boolean

      IS_STACKHAWK_READY:
        default: true
        required: false
        type: boolean

      STACKHAWK_DIRECTORY:
        default: 'stackhawk'
        required: false
        type: string

      STACKHAWK_TMPL_YML:
        default: 'stackhawk-tmpl.yml'
        required: false
        type: string

      IS_FRONTEND:
        default: false
        required: false
        type: boolean

      IS_MONOREPO:
        default: false
        required: false
        type: boolean

      GH_RUNS_ON:
        default: 'ubuntu-latest'
        # default: 'core'
        required: false
        type: string

    outputs:
      NAME:
        value: ${{ jobs.app-setup.outputs.NAME }}
        description: "App/Service name"

      PREVIEW_NAMESPACE:
        value: ${{ jobs.app-setup.outputs.PREVIEW_NAMESPACE }}

      IS_STACKHAWK_READY:
        value: ${{ jobs.app-setup.outputs.IS_STACKHAWK_READY }}

      STACKHAWK_DIRECTORY:
        value: ${{ jobs.app-setup.outputs.STACKHAWK_DIRECTORY }}

jobs:

  app-setup:
    timeout-minutes: 1
    runs-on: ${{ inputs.GH_RUNS_ON }}
    outputs:
      NAME: ${{ steps.set-name.outputs.NAME }}
      PREVIEW_NAMESPACE: ${{ steps.set-name-pr-namespace.outputs.PREVIEW_NAMESPACE }}
      IS_STACKHAWK_READY: ${{ steps.stackhawk-ready-repo.outputs.IS_STACKHAWK_READY }}
      STACKHAWK_DIRECTORY: ${{ steps.stackhawk-ready-repo.outputs.STACKHAWK_DIRECTORY }}
      IS_FRONTEND: ${{ steps.extra-vars.outputs.IS_FRONTEND }}
      IS_MONOREPO: ${{ steps.extra-vars.outputs.IS_MONOREPO }}
    steps:

      - name: "⚠️ Deprecation Warning"
        run: |
          echo "::warning title=Deprecation Notice::This workflow is deprecated. Please use the new workflow instead: setup-app.yaml"
          exit 1
