name: Node and Docker

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      NAME:
        description: "Name of service"
        required: true
        type: string

      VERSION:
        required: true
        type: string

      APP_WORKING_DIR:
        default: '.'
        required: false
        type: string

      SECRETS_TO_FETCH:
        description: "Secrets to fetch from Google Secret Manager"
        required: false
        type: string

      DEFAULT_SECRETS_TO_FETCH:
        description: "Default secrets to fetch from Google Secret Manager"
        required: false
        type: string
        default: |
          GH_TOKEN:projects/1054075584205/secrets/core_GITHUB_FAVEDOM_DEV_PASSWORD,
          NPM_TOKEN:projects/1054075584205/secrets/cicd_NPM_TOKEN

      FILE_DOWNLOAD_BASE_URL:
        default: 'https://raw.githubusercontent.com/favedom-dev/github-reusable-workflow'
        required: false
        type: string

      FILE_GIT_BRANCH:
        default: 'v2.1'
        required: false
        type: string
        description: "Used typically for testing new non-merged helm changes"

      VAR_DOCKER_SCRIPT_NAME:
        default: 'var-docker.sh'
        required: false
        type: string

      PLATFORMS:
        required: false
        type: string
        default: linux/amd64,linux/arm64

      HELM_REPO:
        default: 'https://charts.helm.sh/stable'
        required: false
        type: string

      NODE_VERSION:
        default: "20"
        required: false
        type: string

      CACHE_DEPENDENCY_PATH:
        default: ''
        required: false
        type: string

      UPLOAD_GS:
        default: false
        required: false
        type: boolean

      GS_BUCKET:
        default: 'peeq-public-assets.joinpeeq.com'
        required: false
        type: string

      DOCKER_NAME:
        required: false
        type: string

      DOCKER_ENABLE_CACHE:
        type: string
        default: 'false'
        required: false
        description: "Enable Docker layer caching (true or false)"

      DOCKER_FILE:
        required: false
        type: string

      DOCKER_CONTEXT:
        default: '.'
        required: false
        type: string

      DOCKER_PUSH:
        default: 'true'
        required: false
        type: string

      DOCKER_PUSH_PR:
        default: ''
        required: false
        type: string

      TAG2:
        default: 'latest'
        required: false
        type: string

      PROJECT_ID:
        default: 'favedom-dev'
        required: false
        type: string

      GAR_LOCATION:
        default: 'us-central1'
        required: false
        type: string

      DOCKER_REGISTRY:
        default: 'docker'
        required: false
        type: string

      INSTALL:
        default: true
        required: false
        type: boolean

      INSTALL_NAME:
        default: 'NPM install'
        required: false
        type: string

      INSTALL_CMD:
        default: 'npm install --legacy-peer-deps'
        required: false
        type: string

      TEST:
        default: true
        required: false
        type: boolean

      TEST_NAME:
        default: 'NPM test'
        required: false
        type: string

      TEST_CMD:
        default: 'npm test'
        required: false
        type: string

      BUILD:
        default: true
        required: false
        type: boolean

      BUILD_NAME:
        default: 'NPM build'
        required: false
        type: string

      BUILD_CMD:
        default: 'npm run build'
        required: false
        type: string

      GH_RUNS_ON:
        default: 'ubuntu-latest'
        required: false
        type: string

    secrets:
      # GH_TOKEN:
      #   description: "GitHub token"
      #   required: true

      # NPM_TOKEN:
      #   description: "NPM token"
      #   required: true

      WIF_PROVIDER:
        description: "Workload Identity Federation Provider"
        required: true

      WIF_SERVICE_ACCOUNT:
        description: "Workload Identity Federation Service Account"
        required: true

    outputs:
      ARTIFACT_URL:
        description: "Artifcat URL to specific tag"
        value: ${{ jobs.node-docker.outputs.ARTIFACT_URL }}

jobs:

  node-docker:
    timeout-minutes: 15
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ${{ inputs.GH_RUNS_ON }}
    env:
      # GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      # DOCKER_BUILDKIT: 1
      ARTIFACT_LINK_SCRIPT_NAME: artifact-link.sh
      BUILDKIT_PROGRESS: plain
      DEBUG: 1
    outputs:
      ARTIFACT_URL: ${{ steps.build-docker.outputs.ARTIFACT_URL }}

    steps:

      - name: "☁️ Checkout repository"
        uses: actions/checkout@v4

      - name: "⬇️ Get reusable files"
        uses: favedom-dev/github-reusable-workflow/.github/actions/get-reusable-files@v2.1
        id: get-reusable-files
        with:
          FILE_GIT_BRANCH: ${{ inputs.FILE_GIT_BRANCH }}
          FILE_DOWNLOAD_BASE_URL: ${{ inputs.FILE_DOWNLOAD_BASE_URL }}
          FILES_TO_DOWNLOAD: |
            [
              { "subdirectory": ".github/scripts", "filename": "${{ inputs.VAR_DOCKER_SCRIPT_NAME }}" },
              { "subdirectory": ".github/scripts", "filename": "${{ env.ARTIFACT_LINK_SCRIPT_NAME }}" }
            ]

      - name: "🏷️ Set up variables"
        id: setup-variables
        env:
          DOCKER_NAME: ${{ inputs.DOCKER_NAME }}
          DOCKER_PUSH: ${{ inputs.DOCKER_PUSH }}
          DOCKER_PUSH_PR: ${{ inputs.DOCKER_PUSH_PR }}
          DOCKER_REGISTRY: ${{ inputs.DOCKER_REGISTRY }}
          GAR_LOCATION: ${{ inputs.GAR_LOCATION }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          NAME: ${{ inputs.NAME }}
          PROJECT_ID: ${{ inputs.PROJECT_ID }}
        run: ../${{ inputs.VAR_DOCKER_SCRIPT_NAME }}

      - name: "🔐 Get Secrets"
        uses: favedom-dev/github-reusable-workflow/.github/actions/get-google-secrets@v2.1
        id: get-secrets
        with:
          WIF_PROVIDER: ${{ secrets.WIF_PROVIDER }}
          WIF_SERVICE_ACCOUNT: ${{ secrets.WIF_SERVICE_ACCOUNT }}
          SECRETS_TO_FETCH: ${{ inputs.SECRETS_TO_FETCH }}
          DEFAULT_SECRETS_TO_FETCH: ${{ inputs.DEFAULT_SECRETS_TO_FETCH }}

      - name: "🧰 Set up build basics"
        uses: favedom-dev/github-reusable-workflow/.github/actions/build-setup-basics@v2.1
        id: build-setup-basics
        with:
          GH_RUNS_ON: ${{ inputs.GH_RUNS_ON }}
          PLATFORMS: ${{ inputs.PLATFORMS }}

      - name: "🔧 Set up node.js version: ${{ inputs.NODE_VERSION }}"
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.NODE_VERSION }}
          cache: npm
          cache-dependency-path: ${{ inputs.CACHE_DEPENDENCY_PATH }}

      - name: "📦 Cache node_modules"
        id: cache-node-modules
        # https://github.com/actions/cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.cache-name }}
            ${{ runner.os }}-node-
            ${{ runner.os }}-

      - name: "📝 List the state of node modules"
        continue-on-error: true
        run: npm list

      - name: "🔧 Set up DEPLOY_URL"
        id: set-deploy-url
        if: inputs.UPLOAD_GS == true
        run: |
          if [ "${{ github.event_name }}" != "pull_request" ]; then
            DEPLOY_URL="https://${{ inputs.GS_BUCKET }}/${{ inputs.NAME}}/${{ inputs.VERSION }}/"
            echo "RELEASE DEPLOY_URL: ${DEPLOY_URL}"
          else
            DEPLOY_URL="./"
            echo "PR DEPLOY_URL: ${DEPLOY_URL}"
          fi
          echo "DEPLOY_URL: ${DEPLOY_URL}"
          echo ${DEPLOY_URL} > DEPLOY_URL
          echo "deploy-url=${DEPLOY_URL}" >> $GITHUB_OUTPUT

      - name: "🔄 Update base Url"
        if: inputs.UPLOAD_GS == true
        run: sed -i "s/++DEPLOY_URL++/$(sed -e 's/\//\\\//g' DEPLOY_URL)/g" ./docker/environment.tpl.json

      # - name: "🔧 helm init"
      #   run: |
      #     helm init --client-only --stable-repo-url ${{ inputs.HELM_REPO }}

      - name: "⚙️ Set up .npmrc"
        env:
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ env.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ env.NPM_TOKEN }}" > .npmrc
          # echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: "🪛 ${{ inputs.INSTALL_NAME }}"
        if: inputs.INSTALL == true
        working-directory: ${{ inputs.APP_WORKING_DIR }}
        run: ${{ inputs.INSTALL_CMD }}

      - name: "🔨 ${{ inputs.TEST_NAME }}"
        if: inputs.TEST == true
        working-directory: ${{ inputs.APP_WORKING_DIR }}
        run: ${{ inputs.TEST_CMD }}

      - name: "🛠️ ${{ inputs.BUILD_NAME }}"
        if: inputs.BUILD == true
        working-directory: ${{ inputs.APP_WORKING_DIR }}
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: ${{ inputs.BUILD_CMD }}

      # https://github.com/google-github-actions/upload-cloud-storage
      - name: "⬆️ Release: Upload to Google Storage"
        if: github.event_name != 'pull_request' && inputs.UPLOAD_GS == true
        id: 'upload-folder'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: 'dist/${{ inputs.NAME }}'
          destination: '${{ inputs.GS_BUCKET }}/${{ inputs.NAME }}/${{ inputs.VERSION }}'
          parent: false

      - name: "🐳 Docker"
        uses: favedom-dev/github-reusable-workflow/.github/actions/build-docker@v2.1
        id: build-docker
        with:
          ACCESS_TOKEN: ${{ steps.get-secrets.outputs.access-token }}
          ARTIFACT_LINK_SCRIPT_NAME: ${{ env.ARTIFACT_LINK_SCRIPT_NAME }}
          DOCKER_CONTEXT: ${{ inputs.DOCKER_CONTEXT }}
          DOCKER_ENABLE_CACHE: ${{ inputs. DOCKER_ENABLE_CACHE }}
          DOCKER_FILE: ${{ inputs.DOCKER_FILE }}
          DOCKER_LOCATION: ${{ steps.setup-variables.outputs.DOCKER_LOCATION }}
          DOCKER_PUSH: ${{ steps.setup-variables.outputs.DOCKER_PUSH }}
          DOCKER_URL: ${{ steps.setup-variables.outputs.DOCKER_URL }}
          GAR_LOCATION:  ${{ inputs.GAR_LOCATION }}
          GH_RUNS_ON: ${{ inputs.GH_RUNS_ON }}
          NAME: ${{ inputs.NAME }}
          PLATFORMS: ${{ inputs.PLATFORMS }}
          VERSION: ${{ inputs.VERSION }}

