name: Node and Docker

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      NAME:
        description: "Name of service"
        required: true
        type: string

      VERSION:
        required: true
        type: string

      FILE_DOWNLOAD_BASE_URL:
        default: 'https://raw.githubusercontent.com/favedom-dev/github-reusable-workflow'
        required: false
        type: string

      FILE_GIT_BRANCH:
        default: 'v2'
        required: false
        type: string

      VAR_DOCKER_SCRIPT_NAME:
        default: 'var-docker.sh'
        required: false
        type: string

      PLATFORMS:
        required: false
        type: string
        default: linux/amd64,linux/arm64

      HELM_REPO:
        default: 'https://charts.helm.sh/stable'
        required: false
        type: string

      NODE_VERSION:
        default: "20"
        required: false
        type: string

      UPLOAD_GS:
        default: false
        required: false
        type: boolean

      GS_BUCKET:
        default: 'peeq-public-assets.joinpeeq.com'
        required: false
        type: string

      DOCKER_NAME:
        required: false
        type: string

      DOCKERFILE_FILE:
        default: './Dockerfile'
        required: false
        type: string

      DOCKER_CONTEXT:
        default: '.'
        required: false
        type: string

      DOCKER_PUSH:
        default: 'true'
        required: false
        type: string

      DOCKER_PUSH_PR:
        default: ''
        required: false
        type: string

      TAG2:
        default: 'latest'
        required: false
        type: string

      PROJECT_ID:
        default: 'favedom-dev'
        required: false
        type: string

      GAR_LOCATION:
        default: 'us-central1'
        required: false
        type: string

      DOCKER_REGISTRY:
        default: 'docker'
        required: false
        type: string

      INSTALL:
        default: true
        required: false
        type: boolean

      INSTALL_NAME:
        default: 'NPM install'
        required: false
        type: string

      INSTALL_CMD:
        default: 'npm install --legacy-peer-deps'
        required: false
        type: string

      TEST:
        default: true
        required: false
        type: boolean

      TEST_NAME:
        default: 'NPM test'
        required: false
        type: string

      TEST_CMD:
        default: 'npm test'
        required: false
        type: string

      BUILD:
        default: true
        required: false
        type: boolean

      BUILD_NAME:
        default: 'NPM build'
        required: false
        type: string

      BUILD_CMD:
        default: 'npm run build'
        required: false
        type: string

      GH_RUNS_ON:
        default: 'ubuntu-latest'
        required: false
        type: string

    secrets:
      GH_TOKEN:
        description: "GitHub token"
        required: true

      NPM_TOKEN:
        description: "NPM token"
        required: true

      WIF_PROVIDER:
        description: "Workload Identity Federation Provider"
        required: true

      WIF_SERVICE_ACCOUNT:
        description: "Workload Identity Federation Service Account"
        required: true

jobs:

  node-docker:
    timeout-minutes: 15
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ${{ inputs.GH_RUNS_ON }}
    env:
      # GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      # DOCKER_BUILDKIT: 1
      DOCKER_LINK_SCRIPT_NAME: docker-link.sh
    steps:

      - name: "⬇️ Get reusable files"
        id: get-reusable-files
        run: |
          get_file() {
            FILE_URL=${FILE_DOWNLOAD_BASE_URL}/${FILE_GIT_BRANCH}/${FILE_SUBDIR}/${FILE_NAME}
            echo "Getting ${FILE_NAME} from ${FILE_URL}"
            curl -o ../${FILE_NAME} ${FILE_URL}
            chmod 777 ../${FILE_NAME}
          }
          FILE_GIT_BRANCH=${{ inputs.FILE_GIT_BRANCH }}
          FILE_DOWNLOAD_BASE_URL=${{ inputs.FILE_DOWNLOAD_BASE_URL }}
          FILE_SUBDIR=.github/scripts

          FILE_NAME=${{ inputs.VAR_DOCKER_SCRIPT_NAME }}
          get_file

          FILE_NAME=${DOCKER_LINK_SCRIPT_NAME}
          get_file

      - name: "🏷️ Set up variables"
        id: setup-variables
        env:
          DOCKER_NAME: ${{ inputs.DOCKER_NAME }}
          DOCKER_PUSH: ${{ inputs.DOCKER_PUSH }}
          DOCKER_PUSH_PR: ${{ inputs.DOCKER_PUSH_PR }}
          DOCKER_REGISTRY: ${{ inputs.DOCKER_REGISTRY }}
          GAR_LOCATION: ${{ inputs.GAR_LOCATION }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          NAME: ${{ inputs.NAME }}
          PROJECT_ID: ${{ inputs.PROJECT_ID }}
        run: |
          ../${{ inputs.VAR_DOCKER_SCRIPT_NAME }}

      - name: "🧰 Set up gh cli"
        uses: dev-hanz-ops/install-gh-cli-action@v0.2.1
        if: ${{ !startsWith(inputs.GH_RUNS_ON, 'ubuntu') }}

      - name: "🧰 Set up QEMU"
        uses: docker/setup-qemu-action@v3

      - name: "🧰 Set up Docker Buildx ${{ inputs.PLATFORMS }}"
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ inputs.PLATFORMS }}

      - name: "☁️ Checkout repository"
        uses: actions/checkout@v4

      - name: "🔑 Google Auth Token"
        if: ${{ !env.ACT }}
        id: auth-gcp-token
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      - name: "🔑 Docker Auth"
        if: ${{ !env.ACT }}
        id: auth-docker
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth-gcp-token.outputs.access_token }}'
          registry: '${{ inputs.GAR_LOCATION }}-docker.pkg.dev'  # Google Artifact Registry

      - name: "🔧 Set up node.js version: ${{ inputs.NODE_VERSION }}"
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.NODE_VERSION }}
          cache: npm

      - name: "📦 Cache node_modules"
        id: cache-node-modules
        # https://github.com/actions/cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.cache-name }}
            ${{ runner.os }}-node-
            ${{ runner.os }}-

      - name: "📝 List the state of node modules"
        continue-on-error: true
        run: npm list

      - name: "🔧 Set up DEPLOY_URL"
        id: set-deploy-url
        if: inputs.UPLOAD_GS == true
        run: |
          if [ "${{ github.event_name }}" != "pull_request" ]; then
            DEPLOY_URL="https://${{ inputs.GS_BUCKET }}/${{ inputs.NAME}}/${{ inputs.VERSION }}/"
            echo "RELEASE DEPLOY_URL: ${DEPLOY_URL}"
          else
            DEPLOY_URL="./"
            echo "PR DEPLOY_URL: ${DEPLOY_URL}"
          fi
          echo "DEPLOY_URL: ${DEPLOY_URL}"
          echo ${DEPLOY_URL} > DEPLOY_URL
          echo "deploy-url=${DEPLOY_URL}" >> $GITHUB_OUTPUT

      - name: "🔄 Update base Url"
        if: inputs.UPLOAD_GS == true
        run: sed -i "s/++DEPLOY_URL++/$(sed -e 's/\//\\\//g' DEPLOY_URL)/g" ./docker/environment.tpl.json

      # - name: "🔧 helm init"
      #   run: |
      #     helm init --client-only --stable-repo-url ${{ inputs.HELM_REPO }}

      - name: "⚙️ Set up .npmrc"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: "🪛 ${{ inputs.INSTALL_NAME }}"
        if: inputs.INSTALL == true
        run: ${{ inputs.INSTALL_CMD }}

      - name: "🔨 ${{ inputs.TEST_NAME }}"
        if: inputs.TEST == true
        run: ${{ inputs.TEST_CMD }}

      - name: "🛠️ ${{ inputs.BUILD_NAME }}"
        if: inputs.BUILD == true
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: ${{ inputs.BUILD_CMD }}

      # https://github.com/google-github-actions/upload-cloud-storage
      - name: "⬆️ Release: Upload to Google Storage"
        if: github.event_name != 'pull_request' && inputs.UPLOAD_GS == true
        id: 'upload-folder'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: 'dist/${{ inputs.NAME }}'
          destination: '${{ inputs.GS_BUCKET }}/${{ inputs.NAME }}/${{ inputs.VERSION }}'
          parent: false

      - name: "# Set up Docker tags"
        id: docker-tags
        env:
          # DOCKER_LOCATION: ${{ inputs.GAR_LOCATION }}-docker.pkg.dev/${{ inputs.PROJECT_ID }}/${{ inputs.DOCKER_REGISTRY }}/${{ inputs.NAME }}
          DOCKER_LOCATION: ${{ steps.setup-variables.outputs.DOCKER_LOCATION }}
        run: |-
          DOCKER_TAGS=${{ env.DOCKER_LOCATION }}:${{ inputs.VERSION }}
          if [ "${{ github.event_name }}" != "pull_request" ]; then
            DOCKER_TAGS=$DOCKER_TAGS,${{ env.DOCKER_LOCATION }}:latest
            # echo "IF: DOCKER_TAGS: $DOCKER_TAGS"
          fi
          echo "DOCKER_TAGS: $DOCKER_TAGS"
          echo "tags=$DOCKER_TAGS" >> $GITHUB_OUTPUT

      - name: "🐳 Docker: build, tag, and push"
        # https://github.com/docker/build-push-action
        uses: docker/build-push-action@v6
        if: ${{ !env.ACT }}
        with:
          context: ${{ inputs.DOCKER_CONTEXT }}
          file: ${{ inputs.DOCKERFILE_FILE }}
          platforms: ${{ inputs.PLATFORMS }}
          push: ${{ steps.setup-variables.outputs.DOCKER_PUSH }}
          tags: ${{ steps.docker-tags.outputs.tags }}

      - name: "🔗 Link to Container"
        if: ${{ !env.ACT }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          DOCKER_URL: ${{ steps.setup-variables.outputs.DOCKER_URL }}
          NAME: ${{ inputs.NAME }}
          VERSION: ${{ inputs.VERSION }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |-
          ../${DOCKER_LINK_SCRIPT_NAME}
