name: Maven jar registry

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      NAME:
        description: "Name of service"
        required: true
        type: string

      VERSION:
        required: true
        type: string

      SECRETS_TO_FETCH:
        description: "Secrets to fetch from Google Secret Manager"
        required: false
        type: string

      DEFAULT_SECRETS_TO_FETCH:
        description: "Default secrets to fetch from Google Secret Manager"
        required: false
        type: string
        default: |
          GH_TOKEN:projects/1054075584205/secrets/core_GITHUB_FAVEDOM_DEV_PASSWORD,
          SHIFTLEFT_ACCESS_TOKEN:projects/1054075584205/secrets/cicd_SHIFTLEFT_ACCESS_TOKEN

      FILE_DOWNLOAD_BASE_URL:
        default: 'https://raw.githubusercontent.com/favedom-dev/github-reusable-workflow'
        required: false
        type: string

      FILE_GIT_BRANCH:
        default: 'v2'
        required: false
        type: string
        description: "Used typically for testing new non-merged helm changes"

      JDK_VERSION:
        default: 21
        required: false
        type: number

      JDK_DISTRIBUTION:
        # default: 'temurin'
        default: 'corretto'
        required: false
        type: string

      MVN_VERSION:
        description: "See https://maven.apache.org/docs/history.html"
        default: "3.9.9"
        required: false
        type: string

      MVN_ARGS:
        default: 'clean deploy'
        required: false
        type: string

      MAVEN_WORKING_DIR:
        default: '.'
        required: false
        type: string

      MAVEN_SETTINGS_URL:
        default: 'https://raw.githubusercontent.com/favedom-dev/github-reusable-workflow/master/.m2'
        required: false
        type: string

      PLATFORMS:
        required: false
        type: string
        default: linux/amd64,linux/arm64

      PROJECT_ID:
        default: 'favedom-dev'
        required: false
        type: string

      GAR_LOCATION:
        default: 'us-central1'
        required: false
        type: string

      GAR_MAVEN_URL:
        default: 'https://console.cloud.google.com/artifacts/maven/'
        required: false
        type: string

      MAVEN_REGISTRY:
        default: 'java'
        required: false
        type: string

      JAR_PATH:
        default: 'com.velocityz'
        required: false
        type: string

      SCAN_JAR:
        default: './target/*.jar'
        required: false
        type: string

      VCS_PREFIX_CORRECTION:
        default: 'src/main/java'
        required: false
        type: string

      GH_RUNS_ON:
        default: 'ubuntu-latest'
        required: false
        type: string

    secrets:

      WIF_PROVIDER:
        description: "Workload Identity Federation Provider"
        required: true

      WIF_SERVICE_ACCOUNT:
        description: "Workload Identity Federation Service Account"
        required: true

    outputs:
      ARTIFACT_URL:
        description: "Artifcat URL to specific tag"
        value: ${{ jobs.maven-docker.outputs.ARTIFACT_URL }}

jobs:

  maven-jar:
    timeout-minutes: 15
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ${{ inputs.GH_RUNS_ON }}
    env:
      ARTIFACT_LINK_SCRIPT_NAME: artifact-link.sh
      MVN_SETTINGS_SCRIPT_NAME: mvn-settings.xml.sh
      MVN_SETTINGS_FILE: settings.xml
    outputs:
      ARTIFACT_URL: ${{ steps.artifact-url.outputs.ARTIFACT_URL }}

    steps:

      - name: "☁️ Checkout repository"
        uses: actions/checkout@v4

      - name: "⬇️ Get reusable files"
        uses: favedom-dev/github-reusable-workflow/.github/actions/get-reusable-files@v2
        id: get-reusable-files
        with:
          FILE_GIT_BRANCH: ${{ inputs.FILE_GIT_BRANCH }}
          FILE_DOWNLOAD_BASE_URL: ${{ inputs.FILE_DOWNLOAD_BASE_URL }}
          FILES_TO_DOWNLOAD: |
            [
              { "subdirectory": ".github/scripts", "filename": "${{ env.ARTIFACT_LINK_SCRIPT_NAME }}" },
              { "subdirectory": ".github/scripts", "filename": "${{ env.MVN_SETTINGS_SCRIPT_NAME }}" },
              { "subdirectory": ".m2", "filename": "${{ env.MVN_SETTINGS_FILE }}" }
            ]

      - name: "🏷️ Set up variables"
        id: setup-variables
        run: |
          GAR_URL="${{ inputs.GAR_MAVEN_URL }}${{ inputs.PROJECT_ID }}/${{ inputs.GAR_LOCATION }}/${{ inputs.MAVEN_REGISTRY }}/${{ inputs.JAR_PATH }}:${{ inputs.NAME }}/${{ inputs.VERSION }}?project=${{ inputs.PROJECT_ID }}"
          echo "GAR_URL : ${GAR_URL}"
          echo "GAR_URL=${GAR_URL}" >> $GITHUB_ENV
          echo "GAR_URL=${GAR_URL}" >> $GITHUB_OUTPUT

          ARTIFACT_REGISTRY="artifactregistry://${{ inputs.GAR_LOCATION }}-maven.pkg.dev/${{ inputs.PROJECT_ID }}/${{ inputs.MAVEN_REGISTRY }}"
          echo "ARTIFACT_REGISTRY : ${ARTIFACT_REGISTRY}"
          echo "ARTIFACT_REGISTRY=${ARTIFACT_REGISTRY}" >> $GITHUB_ENV
          echo "ARTIFACT_REGISTRY=${ARTIFACT_REGISTRY}" >> $GITHUB_OUTPUT

          MVN_ARG_ARTIFACT_REGISTRY="-Dartifact.registry=${ARTIFACT_REGISTRY}"
          echo "MVN_ARG_ARTIFACT_REGISTRY : ${MVN_ARG_ARTIFACT_REGISTRY}"
          echo "MVN_ARG_ARTIFACT_REGISTRY=${MVN_ARG_ARTIFACT_REGISTRY}" >> $GITHUB_ENV
          echo "MVN_ARG_ARTIFACT_REGISTRY=${MVN_ARG_ARTIFACT_REGISTRY}" >> $GITHUB_OUTPUT

      - name: "🔐 Get Secrets"
        # TODO
        # uses: favedom-dev/github-reusable-workflow/.github/actions/get-google-secrets@v2
        uses: favedom-dev/github-reusable-workflow/.github/actions/get-google-secrets@FAN-6956-secrets
        id: get-secrets
        with:
          WIF_PROVIDER: ${{ secrets.WIF_PROVIDER }}
          WIF_SERVICE_ACCOUNT: ${{ secrets.WIF_SERVICE_ACCOUNT }}
          SECRETS_TO_FETCH: ${{ inputs.SECRETS_TO_FETCH }}
          DEFAULT_SECRETS_TO_FETCH: ${{ inputs.DEFAULT_SECRETS_TO_FETCH }}

      - name: "🧰 Set up gh cli"
        uses: dev-hanz-ops/install-gh-cli-action@v0.2.1
        if: ${{ !startsWith(inputs.GH_RUNS_ON, 'ubuntu') }}

      - name: "🧰 Set up QEMU"
        uses: docker/setup-qemu-action@v3

      - name: "🧰 Set up Docker Buildx ${{ inputs.PLATFORMS }}"
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ inputs.PLATFORMS }}

      - name: "⚙️ Set up JDK ${{ inputs.JDK_DISTRIBUTION }} ${{ inputs.JDK_VERSION }}"
        uses: actions/setup-java@v4
        with:
          java-version: '${{ inputs.JDK_VERSION }}'
          distribution: '${{ inputs.JDK_DISTRIBUTION }}'

      - name: "⚙️ Set up Maven ${{ inputs.MVN_VERSION }}"
        uses: stCarolas/setup-maven@v5
        if: ${{ !startsWith(github.event.inputs.GH_RUNS_ON, 'ubuntu') }}
        with:
          maven-version: '${{ inputs.MVN_VERSION }}'

      - name: "🧰 Maven ~/.m2/settings.xml"
        run: ../mvn-settings.xml.sh

      - name: "⚙️ Maven set app version ${{ inputs.VERSION }}"
        working-directory: ${{ inputs.MAVEN_WORKING_DIR }}
        run: |
          mvn -B versions:set -DnewVersion=${{ inputs.VERSION }}

      - name: "🛠️ Build with Maven"
        working-directory: ${{ inputs.MAVEN_WORKING_DIR }}
        env:
          MVN_ARG_ARTIFACT_REGISTRY: ${{ steps.setup-variables.outputs.MVN_ARG_ARTIFACT_REGISTRY }}
        run: |
          mvn -B ${{ inputs.MVN_ARGS }} ${MVN_ARG_ARTIFACT_REGISTRY}

      - name: "🔗 Link to Lib"
        # if: steps.setup-variables.outputs.DOCKER_PUSH == 'true'
        id: artifact-url
        env:
          GH_TOKEN: ${{ env.GH_TOKEN }}
          ARTIFACT_TYPE: jar
          ARTIFACT_URL: ${{ steps.setup-variables.outputs.GAR_URL }}
          NAME: ${{ inputs.NAME }}
          VERSION: ${{ inputs.VERSION }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: ../${ARTIFACT_LINK_SCRIPT_NAME}

      - name: "⬇️ Download Qwiet CLI"
        uses: favedom-dev/github-reusable-workflow/.github/actions/qwiet-download-cli@v2
        with:
          shiftleft-access-token: ${{ env.SHIFTLEFT_ACCESS_TOKEN }}

      - name: "🔍 Qwiet Analyze with NextGen Static Analysis"
        uses: favedom-dev/github-reusable-workflow/.github/actions/qwiet-analyze@v2
        with:
          shiftleft-access-token: ${{ env.SHIFTLEFT_ACCESS_TOKEN }}
          name: ${{ inputs.NAME }}
          vcs-prefix-correction: ${{ inputs.VCS_PREFIX_CORRECTION }}
          scan-jar: ${{ inputs.SCAN_JAR }}
