name: Maven and Docker

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:

      NAME:
        description: "Name of service"
        required: true
        type: string

      VERSION:
        required: true
        type: string

      secrets-to-fetch:
        description: "Secrets to fetch from Google Secret Manager"
        required: false
        type: string

      default-secrets-to-fetch:
        description: "Default secrets to fetch from Google Secret Manager"
        required: false
        type: string
        default: |
          GH_TOKEN:projects/1054075584205/secrets/core_GITHUB_FAVEDOM_DEV_PASSWORD

      FILE_DOWNLOAD_BASE_URL:
        default: 'https://raw.githubusercontent.com/favedom-dev/github-reusable-workflow'
        required: false
        type: string

      FILE_GIT_BRANCH:
        default: 'v2'
        required: false
        type: string
        description: "Used typically for testing new non-merged helm changes"

      VAR_DOCKER_SCRIPT_NAME:
        default: 'var-docker.sh'
        required: false
        type: string

      APP_WORKING_DIR:
        default: '.'
        required: false
        type: string

      JDK_VERSION:
        default: 21
        required: false
        type: number

      JDK_DISTRIBUTION:
        # default: 'temurin'
        default: 'corretto'
        required: false
        type: string

      MVN_VERSION:
        description: "See https://maven.apache.org/docs/history.html"
        default: "3.9.9"
        required: false
        type: string

      MVN_ENV_VARS:
        description: "-DmyVariable=someValue"
        required: false
        type: string

      MVN_ARGS:
        default: 'clean install'
        required: false
        type: string

      MVN_ARGS_EXTRA:
        required: false
        type: string

      PLATFORMS:
        required: false
        type: string
        default: linux/amd64,linux/arm64

      DOCKER_NAME:
        required: false
        type: string

      DOCKERFILE_FILE:
        default: './Dockerfile'
        required: false
        type: string

      DOCKER_PUSH:
        default: 'true'
        required: false
        type: string

      DOCKER_PUSH_PR:
        default: ''
        required: false
        type: string

      TAG2:
        default: 'latest'
        required: false
        type: string

      PROJECT_ID:
        default: 'favedom-dev'
        required: false
        type: string

      GAR_LOCATION:
        default: 'us-central1'
        required: false
        type: string

      DOCKER_REGISTRY:
        default: 'docker'
        required: false
        type: string

      CREATE_CREDENTIALS_FILE:
        default: true
        required: false
        type: boolean

      EXPORT_ENVIRONMENT_VARIABLES:
        default: true
        required: false
        type: boolean

      RUN_GCP_JSON_KEY:
        default: false
        required: false
        type: boolean

      SCAN_JAR:
        default: './target/*.jar'
        required: false
        type: string

      VCS_PREFIX_CORRECTION:
        default: 'src/main/java'
        required: false
        type: string

      GH_RUNS_ON:
        default: 'ubuntu-latest'
        required: false
        type: string

    secrets:

      SECRETS_JSON:
        description: "secrets JSON"
        required: false

      WIF_PROVIDER:
        description: "Workload Identity Federation Provider"
        required: true

      WIF_SERVICE_ACCOUNT:
        description: "Workload Identity Federation Service Account"
        required: true

      GH_TOKEN:
        description: "GitHub token"
        # required: true
        required: false

      GCP_JSON_KEY:
        required: false

      MVN_ARGS_SECRETS:
        description: "Maven args that contain secrets"
        required: false

      SHIFTLEFT_ACCESS_TOKEN:
        description: "Shiftleft/Qwiet token"
        required: false

    outputs:

      ARTIFACT_URL:
        description: "Artifcat URL to specific tag"
        value: ${{ jobs.maven-docker.outputs.ARTIFACT_URL }}

jobs:

  maven-docker:
    timeout-minutes: 15
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ${{ inputs.GH_RUNS_ON }}
    env:
      # GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      # DOCKER_BUILDKIT: 1
      ARTIFACT_LINK_SCRIPT_NAME: artifact-link.sh
      MVN_SETTINGS_SCRIPT_NAME: mvn-settings.xml.sh
      MVN_SETTINGS_FILE: settings.xml
    outputs:
      ARTIFACT_URL: ${{ steps.artifact-url.outputs.ARTIFACT_URL }}

    steps:

      # - name: "📄 GITHUB INFO"
      #   uses: favedom-dev/github-reusable-workflow/.github/actions/debug-github-info@v2
      #   with:
      #     github-context: ${{ toJSON(github) }}
      #     event-name: ${{ github.event_name }}
      #     run-attempt: ${{ github.run_attempt }}
      #     run-number: ${{ github.run_number }}
      #     pr-number: ${{ github.event.pull_request.number }}

      - name: "☁️ Checkout repository"
        uses: actions/checkout@v4

      - name: "⬇️ Get reusable files"
        uses: favedom-dev/github-reusable-workflow/.github/actions/get-reusable-files@v2
        id: get-reusable-files
        with:
          FILE_GIT_BRANCH: ${{ inputs.FILE_GIT_BRANCH }}
          FILE_DOWNLOAD_BASE_URL: ${{ inputs.FILE_DOWNLOAD_BASE_URL }}
          FILES_TO_DOWNLOAD: |
            [
              { "subdirectory": ".github/scripts", "filename": "${{ inputs.VAR_DOCKER_SCRIPT_NAME }}" },
              { "subdirectory": ".github/scripts", "filename": "${{ env.ARTIFACT_LINK_SCRIPT_NAME }}" },
              { "subdirectory": ".github/scripts", "filename": "${{ env.MVN_SETTINGS_SCRIPT_NAME }}" },
              { "subdirectory": ".m2", "filename": "${{ env.MVN_SETTINGS_FILE }}" }
            ]

      - name: "🏷️ Set up variables"
        id: setup-variables
        env:
          DOCKER_NAME: ${{ inputs.DOCKER_NAME }}
          DOCKER_PUSH: ${{ inputs.DOCKER_PUSH }}
          DOCKER_PUSH_PR: ${{ inputs.DOCKER_PUSH_PR }}
          DOCKER_REGISTRY: ${{ inputs.DOCKER_REGISTRY }}
          GAR_LOCATION: ${{ inputs.GAR_LOCATION }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          NAME: ${{ inputs.NAME }}
          PROJECT_ID: ${{ inputs.PROJECT_ID }}
        run: ../${{ inputs.VAR_DOCKER_SCRIPT_NAME }}

      - name: "🔐 Get Secrets"
        # uses: favedom-dev/github-reusable-workflow/.github/actions/get-google-secrets@v2
        uses: favedom-dev/github-reusable-workflow/.github/actions/get-google-secrets@FAN-6956-secrets
        with:
          WIF_PROVIDER: ${{ secrets.WIF_PROVIDER }}
          WIF_SERVICE_ACCOUNT: ${{ secrets.WIF_SERVICE_ACCOUNT }}
          secrets-to-fetch: ${{ inputs.secrets-to-fetch }}
          default-secrets-to-fetch: ${{ inputs.default-secrets-to-fetch }}

      - name: "⚙️ Set MVN_ARGS_SECRETS"
        id: set-mvn-args-secrets
        env:
          SECRETS_TO_FETCH: '${{ inputs.secrets-to-fetch }}'
        run: |
          MVN_ARGS_SECRETS=""
          echo "inputs.secrets-to-fetch : $SECRETS_TO_FETCH"

          if [ -n "${SECRETS_TO_FETCH}" ]; then
            # Remove possible newlines and extra whitespace
            CLEANED_SECRETS=$(echo "${SECRETS_TO_FETCH}" | tr -d '\n' | sed 's/ //g')

            IFS=',' read -ra SECRETS <<< "${CLEANED_SECRETS}"
            for secret in "${SECRETS[@]}"; do
              secret_key=$(echo "${secret}" | cut -d':' -f1)
              secret_value=$(echo "${secret}" | cut -d':' -f2-)

              echo "secret_key   : ${secret_key}"
              echo "secret_value : ${secret_value}"

              if [[ "${secret_key}" == MVN_ARGS__* ]]; then
                mvn_arg_key="${secret_key#MVN_ARGS__}"
                echo "mvn_arg_key  : ${mvn_arg_key}"

                mvn_arg_value=$(echo "${!secret_key}")
                # echo "mvn_arg_value: ${mvn_arg_value}"

                if [[ -z "$MVN_ARGS_SECRETS" ]]; then
                  MVN_ARGS_SECRETS="-D${mvn_arg_key}=${mvn_arg_value}"
                else
                  MVN_ARGS_SECRETS="${MVN_ARGS_SECRETS} -D${mvn_arg_key}=${mvn_arg_value}"
                fi
              else
                echo "Variable does NOT start with MVN_ARGS__"
              fi
            done
          fi

          echo "MVN_ARGS_SECRETS : ${MVN_ARGS_SECRETS}"
          echo "MVN_ARGS_SECRETS=${MVN_ARGS_SECRETS}" >> $GITHUB_OUTPUT

      - name: "🧰 Set up gh cli"
        uses: dev-hanz-ops/install-gh-cli-action@v0.2.1
        if: ${{ !startsWith(inputs.GH_RUNS_ON, 'ubuntu') }}

      - name: "🧰 Set up QEMU"
        uses: docker/setup-qemu-action@v3

      - name: "🧰 Set up Docker Buildx ${{ inputs.PLATFORMS }}"
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ inputs.PLATFORMS }}

      # - name: "🔑 Google Auth Token"
      #   id: auth-gcp-token
      #   uses: 'google-github-actions/auth@v2'
      #   with:
      #     token_format: 'access_token'
      #     workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
      #     service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'
      #     create_credentials_file: ${{ inputs.CREATE_CREDENTIALS_FILE }}
      #     export_environment_variables: ${{ inputs.EXPORT_ENVIRONMENT_VARIABLES }}

      - name: "🗝️ Google Auth JSON Key"
        id: auth-gcp-key
        if: inputs.RUN_GCP_JSON_KEY
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_JSON_KEY }}'

      # https://github.com/google-github-actions/setup-gcloud
      # - name: "🧰 Set up Cloud SDK"
      #   uses: 'google-github-actions/setup-gcloud@v0'

      - name: "🔑 Docker Auth: GAR"
        if: ${{ !env.ACT }}
        id: auth-docker
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth-gcp-token.outputs.access_token }}'
          registry: '${{ inputs.GAR_LOCATION }}-docker.pkg.dev'  # Google Artifact Registry

      - name: "⚙️ Set up JDK ${{ inputs.JDK_DISTRIBUTION }} ${{ inputs.JDK_VERSION }}"
        uses: actions/setup-java@v4
        with:
          java-version: '${{ inputs.JDK_VERSION }}'
          distribution: '${{ inputs.JDK_DISTRIBUTION }}'

      - name: "⚙️ Set up Maven ${{ inputs.MVN_VERSION }}"
        uses: stCarolas/setup-maven@v5
        if: ${{ !startsWith(inputs.GH_RUNS_ON, 'ubuntu') }}
        with:
          maven-version: '${{ inputs.MVN_VERSION }}'

      - name: "📦 Cache local Maven repository"
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ inputs.NAME }}-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ inputs.NAME }}-${{ runner.os }}-maven-

      - name: "🧰 Maven ~/.m2/settings.xml"
        run: ../mvn-settings.xml.sh

      - name: "⚙️ Maven set app version ${{ inputs.VERSION }}"
        working-directory: ${{ inputs.APP_WORKING_DIR }}
        env:
          VERSION: ${{ inputs.VERSION }}
        run: |
          mvn -B versions:set -DnewVersion=${VERSION}

      - name: "🛠️ Build with Maven"
        working-directory: ${{ inputs.APP_WORKING_DIR }}
        env:
          GCP_ACCESS_TOKEN: '${{ steps.auth-gcp-token.outputs.access_token }}'
          GCP_ACCESS_TOKEN_EXPIRATION: '${{ steps.auth-gcp-token.outputs.access_token_expiration }}'
        run: |
          echo "MVN_ARGS        : ${{ inputs.MVN_ARGS }}"
          echo "MVN_ENV_VARS    : ${{ inputs.MVN_ENV_VARS }}"
          echo "MVN_ARGS_EXTRA  : ${{ inputs.MVN_ARGS_EXTRA }}"
          # echo "MVN_ARGS_SECRETS: ${{ secrets.MVN_ARGS_SECRETS }}"
          echo "MVN_ARGS_SECRETS: ${{ steps.set-mvn-args-secrets.outputs.MVN_ARGS_SECRETS }}"
          mvn -B \
          ${{ steps.set-mvn-args-secrets.outputs.MVN_ARGS_SECRETS }} \
          ${{ inputs.MVN_ENV_VARS }} \
          ${{ inputs.MVN_ARGS }} \
          ${{ inputs.MVN_ARGS_EXTRA }}

      - name: "⬇️ Download Qwiet CLI"
        uses: favedom-dev/github-reusable-workflow/.github/actions/qwiet-download-cli@v2
        with:
          shiftleft-access-token: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}

      - name: "🔍 Qwiet Analyze with NextGen Static Analysis"
        uses: favedom-dev/github-reusable-workflow/.github/actions/qwiet-analyze@v2
        with:
          shiftleft-access-token: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
          name: ${{ inputs.NAME }}
          vcs-prefix-correction: ${{ inputs.VCS_PREFIX_CORRECTION }}
          scan-jar: ${{ inputs.SCAN_JAR }}

      - name: "# Set up Docker tags"
        uses: favedom-dev/github-reusable-workflow/.github/actions/set-docker-tags@v2
        id: docker-tags
        with:
          VERSION: ${{ inputs.VERSION }}
          DOCKER_LOCATION: ${{ steps.setup-variables.outputs.DOCKER_LOCATION }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}

      - name: "🐳 Docker: build, tag, and push"
        uses: docker/build-push-action@v6
        id: docker-build
        if: ${{ !env.ACT }}
        with:
          context: ${{ inputs.APP_WORKING_DIR }}
          # file: ${{ env.DOCKERFILE_FILE }}
          platforms: ${{ inputs.PLATFORMS }}
          push: ${{ steps.setup-variables.outputs.DOCKER_PUSH }}
          tags: ${{ steps.docker-tags.outputs.tags }}

      - name: "🔗 Link to Container"
        if: steps.setup-variables.outputs.DOCKER_PUSH == 'true'
        id: artifact-url
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ARTIFACT_DIGEST: ${{ steps.docker-build.outputs.digest }}
          # ARTIFACT_TYPE: docker
          ARTIFACT_URL: ${{ steps.setup-variables.outputs.DOCKER_URL }}
          NAME: ${{ inputs.NAME }}
          VERSION: ${{ inputs.VERSION }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: ../${ARTIFACT_LINK_SCRIPT_NAME}
