name: CI

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:

  # lint-yaml:
  #   if: github.event_name == 'pull_request'
  #   # uses: favedom-dev/github-reusable-workflow/.github/workflows/lint-yaml.yaml@master
  #   uses: ./.github/workflows/lint-yaml.yaml
  #   with:
  #     YAML_DIRS: '.github templates'

  repo-version:
    if: github.event_name != 'pull_request'
    uses: favedom-dev/github-reusable-workflow/.github/workflows/repo-version.yaml@master
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
