name: Deploy Environment

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      NAME:  # name of component, (ex: peeq-tracking)
        required: true
        type: string
      VERSION:
        required: true
        type: string
      ENV_REPO_NAME:
        # default: 'favedom-dev/environment-???'  # ArgoCD
        default: 'favedom-dev/environment-favedom-dev-staging'
        required: false
        type: string
      ENV_REPO_PATH:
        default: 'env-repo'
        required: false
        type: string
      ENV_REPO_SUBDIR:
        # default: 'staging'  # ArgoCD
        default: '.'  # JX
        required: false
        type: string
      YAML_FILE:
        # default: 'requirements.yaml'  # ArgoCD
        default: 'helmfile.yaml'  # JX
        required: false
        type: string
      YAML_ELEMENT:
        # default: 'dependencies'  # ArgoCD
        default: 'releases'  # JX
        required: false
        type: string
    secrets:
      GH_TOKEN:  # GitHub token
        required: true

jobs:

  deploy-environment:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:

      - name: "🔧 Git config"
        if: github.ref == 'refs/heads/master'
        run: |
          git config --global user.email ""
          git config --global user.name "velocityz-0x-pq-github"

      - name: "☁️ Checkout environment repository: ${{ inputs.ENV_REPO_NAME }}"
        if: github.ref == 'refs/heads/master'
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.ENV_REPO_NAME }}
          token: ${{ secrets.GH_TOKEN }}
          ref: master
          path: ${{ inputs.ENV_REPO_PATH }}

      - name: "Update version in environment repo: ${{ inputs.YAML_FILE }}"
        working-directory: ${{ inputs.ENV_REPO_PATH }}
# yamllint disable
        run: |
          yq \
          eval \
          --prettyPrint \
          "(.${{ inputs.YAML_ELEMENT }}[] | select(has(\"name\")) | select(.name == \"${{ inputs.NAME }}\")).version = \"${{ inputs.VERSION }}\"" \
          -i ./${{ inputs.YAML_FILE }}
# yamllint enable

#       - name: "DEBUG: ./${{ inputs.YAML_FILE }}"
#         if: github.ref == 'refs/heads/master'
# # yamllint disable
#         working-directory: ${{ inputs.ENV_REPO_PATH }}/${{ inputs.ENV_REPO_SUBDIR }}
# # yamllint enable
#         run: |
#           cat ./${{ inputs.YAML_FILE }}

      - name: "Create environment PR"
        if: github.ref == 'refs/heads/master'
        working-directory: ${{ inputs.ENV_REPO_PATH }}
        env:
          NAME: ${{ inputs.NAME }}
          VERSION: ${{ inputs.VERSION }}
          BRANCH_NAME: gha_${{ inputs.NAME }}_${{ inputs.VERSION }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
# yamllint disable
        run: |
          git checkout -b ${BRANCH_NAME}
          git commit -a -m "${NAME} ${VERSION}"
          git push -u origin ${BRANCH_NAME}
          gh pr create --label "approved" --title "chore: bump ${NAME} to ${VERSION}" --body "${NAME} ${VERSION}"
          # gh pr merge --auto
# yamllint enable
