name: Deploy Environment

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      NAME:
        required: true
        type: string

      VERSION:
        required: true
        type: string

      DEPENDENCY_NAME:
        default: ''
        required: false
        type: string

      SECRETS_TO_FETCH:
        description: "Secrets to fetch from Google Secret Manager"
        required: false
        type: string

      DEFAULT_SECRETS_TO_FETCH:
        description: "Default secrets to fetch from Google Secret Manager"
        required: false
        type: string
        default: |
          GH_TOKEN:projects/1054075584205/secrets/core_GITHUB_FAVEDOM_DEV_PASSWORD

      MONOREPO_APP:
        default: ''
        required: false
        type: string

      ENV_REPO_NAME:
        default: 'favedom-dev/argocd-deployments'
        required: false
        type: string

      ENV_REPO_BRANCH:
        default: 'master'
        required: false
        type: string

      ENV_REPO_PATH:
        default: 'env-repo'
        required: false
        type: string

      ENV_REPO_SUBDIR_BASE:
        default: 'dev/fanfuzenil'
        required: false
        type: string

      ENV_REPO_SUBDIR:
        required: false
        type: string

      OVERRIDE_SUBDIR_NAME:
        required: false
        type: string

      DO_PR_MERGE:
        default: 'true'
        required: false
        type: string

      VERSION_SCRIPT_BASE_URL:
        default: 'https://raw.githubusercontent.com/favedom-dev/github-reusable-workflow'
        required: false
        type: string

      VERSION_SCRIPT_BRANCH:
        default: 'v2.1'
        required: false
        type: string

      VERSION_SCRIPT_DIR:
        default: '.github/scripts'
        required: false
        type: string

      VERSION_SCRIPT_NAME:
        default: 'update-values-tag.sh'
        required: false
        type: string

      YAML_FILE:
        default: 'values.yaml'
        required: false
        type: string

      GH_USER_NAME:
        default: 'PowerVZ GitHub Bot'
        required: false
        type: string

      GH_USER_EMAIL:
        # default: 'github@powervz.com'
        default: ''
        required: false
        type: string

      GH_RUNS_ON:
        default: 'ubuntu-latest'
        required: false
        type: string

    secrets:

      WIF_PROVIDER:
        description: "Workload Identity Federation Provider"
        required: true

      WIF_SERVICE_ACCOUNT:
        description: "Workload Identity Federation Service Account"
        required: true

jobs:

  deploy-environment:
    timeout-minutes: 5
    runs-on: ${{ inputs.GH_RUNS_ON }}
    permissions:
      id-token: write
      contents: read
    steps:

      # - name: "🕸️ DEBUG: inputs"
      #   run: |
      #     echo "NAME                    : ${{ inputs.NAME }}"
      #     echo "VERSION                 : ${{ inputs.VERSION }}"
      #     echo "MONOREPO_APP            : ${{ inputs.MONOREPO_APP }}"
      #     echo "ENV_REPO_NAME           : ${{ inputs.ENV_REPO_NAME }}"
      #     echo "ENV_REPO_BRANCH         : ${{ inputs.ENV_REPO_BRANCH }}"
      #     echo "ENV_REPO_PATH           : ${{ inputs.ENV_REPO_PATH }}"
      #     echo "ENV_REPO_SUBDIR_BASE    : ${{ inputs.ENV_REPO_SUBDIR_BASE }}"
      #     echo "ENV_REPO_SUBDIR         : ${{ inputs.ENV_REPO_SUBDIR }}"
      #     echo "OVERRIDE_SUBDIR_NAME    : ${{ inputs.OVERRIDE_SUBDIR_NAME }}"
      #     echo "VERSION_SCRIPT_BASE_URL : ${{ inputs.VERSION_SCRIPT_BASE_URL }}"
      #     echo "VERSION_SCRIPT_BRANCH   : ${{ inputs.VERSION_SCRIPT_BRANCH }}"
      #     echo "VERSION_SCRIPT_DIR      : ${{ inputs.VERSION_SCRIPT_DIR }}"
      #     echo "VERSION_SCRIPT_NAME     : ${{ inputs.VERSION_SCRIPT_NAME }}"
      #     echo "YAML_FILE               : ${{ inputs.YAML_FILE }}"

      - name: "⬇️ Get reusable files"
        uses: favedom-dev/github-reusable-workflow/.github/actions/get-reusable-files@v2.1
        id: get-reusable-files
        with:
          FILE_GIT_BRANCH: ${{ inputs.VERSION_SCRIPT_BRANCH }}
          FILE_DOWNLOAD_BASE_URL: ${{ inputs.VERSION_SCRIPT_BASE_URL }}
          FILES_TO_DOWNLOAD: |
            [
              { "subdirectory": "${{ inputs.VERSION_SCRIPT_DIR }}", "filename": "${{ inputs.VERSION_SCRIPT_NAME }}" }
            ]

      - name: "🔐 Get Secrets"
        uses: favedom-dev/github-reusable-workflow/.github/actions/get-google-secrets@v2.1
        id: get-secrets
        with:
          WIF_PROVIDER: ${{ secrets.WIF_PROVIDER }}
          WIF_SERVICE_ACCOUNT: ${{ secrets.WIF_SERVICE_ACCOUNT }}
          SECRETS_TO_FETCH: ${{ inputs.SECRETS_TO_FETCH }}
          DEFAULT_SECRETS_TO_FETCH: ${{ inputs.DEFAULT_SECRETS_TO_FETCH }}

      - name: "🔩 Git config"
        uses: favedom-dev/github-reusable-workflow/.github/actions/setup-git-config@v2.1
        with:
          GH_USER_NAME: ${{ inputs.GH_USER_NAME }}
          GH_USER_EMAIL: ${{ inputs.GH_USER_EMAIL }}

      - name: "☁️ Checkout environment repository: ${{ inputs.ENV_REPO_NAME }} branch: ${{ inputs.ENV_REPO_BRANCH }}"
        if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.ENV_REPO_NAME }}
          token: ${{ env.GH_TOKEN }}
          ref: ${{ inputs.ENV_REPO_BRANCH }}
          path: ${{ inputs.ENV_REPO_PATH }}

      - name: "📝 Set ENV_REPO_SUBDIR"
        id: set-env-repo-subdir
        env:
          OVERRIDE_SUBDIR_NAME: ${{ inputs.OVERRIDE_SUBDIR_NAME }}
          SUBDIR_NAME: ${{ inputs.NAME }}
        run: |
          echo "SUBDIR_NAME         : ${SUBDIR_NAME}"
          echo "OVERRIDE_SUBDIR_NAME: ${OVERRIDE_SUBDIR_NAME}"
          if [ -n "${ENV_REPO_SUBDIR}" ]; then
            ENV_REPO_SUBDIR=${{ inputs.ENV_REPO_SUBDIR }}
            echo "if ENV_REPO_SUBDIR: ${ENV_REPO_SUBDIR}"
          else
            if [ -n "${OVERRIDE_SUBDIR_NAME}" ]; then
              SUBDIR_NAME=${{ inputs.OVERRIDE_SUBDIR_NAME }}
            fi
            ENV_REPO_SUBDIR=${{ inputs.ENV_REPO_SUBDIR_BASE }}/${SUBDIR_NAME}
            echo "else ENV_REPO_SUBDIR: ${ENV_REPO_SUBDIR}"
          fi
          echo "ENV_REPO_SUBDIR: ${ENV_REPO_SUBDIR}"
          echo "ENV_REPO_SUBDIR=${ENV_REPO_SUBDIR}" >> $GITHUB_OUTPUT

      - name: "👁️‍🗨️ PRE-update: ./${{ inputs.YAML_FILE }}"
        if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        working-directory: ${{ inputs.ENV_REPO_PATH }}/${{ steps.set-env-repo-subdir.outputs.ENV_REPO_SUBDIR }}
        run: |
          pwd
          cat ./${{ inputs.YAML_FILE }}

      - name: "🔄 Update ${{ inputs.NAME }} version ${{ inputs.VERSION }} in environment repo: ${{ inputs.YAML_FILE }}"
        if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        working-directory: ${{ inputs.ENV_REPO_PATH }}/${{ steps.set-env-repo-subdir.outputs.ENV_REPO_SUBDIR }}
        env:
          DEPENDENCY_NAME: ${{ inputs.DEPENDENCY_NAME }}
          NAME: ${{ inputs.NAME }}
          VERSION: ${{ inputs.VERSION }}
          VERSION_SCRIPT_DIR_URL: ${{ inputs.VERSION_SCRIPT_BASE_URL }}/${{ inputs.VERSION_SCRIPT_BRANCH }}/${{ inputs.VERSION_SCRIPT_DIR }}
          VERSION_SCRIPT_NAME: ${{ inputs.VERSION_SCRIPT_NAME }}
          YAML_FILE: ${{ inputs.YAML_FILE }}
        run: |
          echo "Update values.yaml ${NAME}.image.tag"
          if [ -f "${{ github.workspace }}/../${{ inputs.VERSION_SCRIPT_NAME }}" ]; then
            echo "Copying ${{ inputs.VERSION_SCRIPT_NAME }}"
            cp ${{ github.workspace }}/../${{ inputs.VERSION_SCRIPT_NAME }} ./${{ inputs.VERSION_SCRIPT_NAME }}
          else
            echo "File does not exist: ${{ github.workspace }}/../${{ inputs.VERSION_SCRIPT_NAME }}"
          fi

          UPDATE_NAME="${NAME}"
          if [ ${{ inputs.VERSION_SCRIPT_NAME }} == 'update-values-tag.sh' ]; then
            echo "Using update-values-tag.sh script"
            if [ -n "${DEPENDENCY_NAME}" ]; then
              echo "Using dependency name: ${DEPENDENCY_NAME}"
              UPDATE_NAME="${DEPENDENCY_NAME}"
            fi
          else
            echo "Using custom script: ${{ inputs.VERSION_SCRIPT_NAME }}"
          fi

          TARGET_DIR="."

          echo "Running script: ./${{ inputs.VERSION_SCRIPT_NAME }} ${TARGET_DIR} ${UPDATE_NAME} ${{ inputs.VERSION }}"
          ./${{ inputs.VERSION_SCRIPT_NAME }} "${TARGET_DIR}" "${UPDATE_NAME}" "${{ inputs.VERSION }}"

          echo "Cleaning up script file"
          rm ./${{ inputs.VERSION_SCRIPT_NAME }}

          echo ""
          echo "🛈 NOTE: MAY NEED TO EXPAND THIS!!!"

      - name: "👁️ Updated: ./${{ inputs.YAML_FILE }}"
        if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        working-directory: ${{ inputs.ENV_REPO_PATH }}/${{ steps.set-env-repo-subdir.outputs.ENV_REPO_SUBDIR }}
        run: |
          pwd
          cat ./${{ inputs.YAML_FILE }}

      - name: "🡢 Create environment PR in repo: ${{ inputs.ENV_REPO_NAME }}"
        uses: favedom-dev/github-reusable-workflow/.github/actions/create-env-pr@v2.1
        if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        with:
          do-pr-merge: ${{ inputs.DO_PR_MERGE }}
          env-repo-name: ${{ inputs.ENV_REPO_NAME }}
          env-repo-path: ${{ inputs.ENV_REPO_PATH }}
          gh-token: ${{ env.GH_TOKEN }}
          is-helm-chart: 'false'
          init-pr-sleep-time: '60'
          monorepo-app: ${{ inputs.MONOREPO_APP }}
          name: ${{ inputs.NAME }}
          version: ${{ inputs.VERSION }}
