name: Deploy jar registry

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      NAME:  # name of service, (ex: peeq-tracking)
        required: true
        type: string
      VERSION:
        required: true
        type: string
      MVN_ARGS:
        default: 'clean deploy'
        required: false
        type: string
      DOCKERFILE_FILE:
        default: './Dockerfile'
        required: false
        type: string
      TAG2:
        default: 'latest'
        required: false
        type: string
      PROJECT_ID:
        default: 'favedom-dev'
        required: false
        type: string
      GAR_LOCATION:
        default: 'us-central1'
        required: false
        type: string
      DOCKER_REGISTRY:
        default: 'peeq-docker'
        required: false
        type: string
    secrets:
      GH_TOKEN:  # GitHub token
        required: true
      WIF_PROVIDER:  # Workload Identity Federation Provider
        required: true
      WIF_SERVICE_ACCOUNT:  # Workload Identity Federation Service Account
        required: true
      NEXUS_FAVEDOM_DEV_PASSWORD:
        required: true

jobs:

  deploy-jar-registry:
    timeout-minutes: 15
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:

      - name: "☁️ Checkout repository"
        uses: actions/checkout@v3

      - name: "🔧 Set up JDK 11"
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: "🔧 Maven ~/.m2/settings.xml"
        env:
          NEXUS_FAVEDOM_DEV_PASSWORD: ${{ secrets.NEXUS_FAVEDOM_DEV_PASSWORD }}
        run: |
          wget https://raw.githubusercontent.com/favedom-dev/github-reusable-workflow/master/.m2/settings.xml
          envsubst < ./settings.xml > ~/.m2/settings.xml

      - name: "🔨 Maven set version"
        run: |
          mvn versions:set -DnewVersion=${{ inputs.VERSION }}

      - name: "🔨 Build with Maven"
        # run: mvn ${{ inputs.MVN_ARGS }}
        run: mvn deploy

      # - name: "🔧 Google Auth"
      #   if: ${{ !env.ACT }}
      #   id: auth
      #   uses: 'google-github-actions/auth@v0'
      #   with:
      #     token_format: 'access_token'
      #     workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
      #     service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'
