name: Example

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      VER:
        required: true
        type: string

jobs:

  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:

      - name: ECHO version
        run: |
          echo "VERSION: ${{ needs.repo-get-version.outputs.version }}"
          echo "VER: ${{ inputs.VER }}"
