name: Get Repo Version

# To use version add to job `needs: get-version`
# Then version is accessible via ${{ needs.++JOB++.outputs.version }} || ${{ needs.get-version.outputs.version }}

on:
  workflow_call:
    secrets:
      GH_TOKEN: # GitHub token
        required: true
    outputs:
      version:
        description: "Repo Version"
        value: ${{ jobs.version.outputs.version }}

jobs:

  get-repo-version:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    outputs:
      version: ${{ steps.version.outputs.version  }}
    steps:

      - name: "☁️ Checkout repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "☑ Release version"
        id: version
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch
          tag_prefix: v
          dry_run: true

      - name: DISPLAY version
        run: |
          echo "${{ steps.version.outputs.version }}"
