name: Lint Yaml (yamllint)
# Reusable workflow to lint YAML files using yamllint.

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      YAML_DIRS:
        description: "Directories containing YAML files to lint"
        default: '.'
        required: false
        type: string

      PYTHON_VERSION:
        description: "Python version for linting tools"
        default: "3.8"
        required: false
        type: string

      GH_RUNS_ON:
        description: "GitHub Actions runner label to use"
        default: 'ubuntu-latest'
        required: false
        type: string

jobs:

  lint-yaml:
    timeout-minutes: 10
    runs-on: ${{ inputs.GH_RUNS_ON }}
    steps:

      - name: "☁️ Checkout repository"
        uses: actions/checkout@v4

      - name: "🧰 Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: "${{ inputs.PYTHON_VERSION }}"

      # https://yamllint.readthedocs.io/en/stable/
      - name: "🪛 Install yamllint"
        run: pip install --user yamllint

      # - name: "⚙️ Config yamllint"
      #   run: |
      #     wget https://raw.githubusercontent.com/favedom-dev/github-reusable-workflow/master/.yamllint
      #     chmod 777 .yamllint
      #     echo "==="
      #     cat .yamllint

      # - name: "👁️ yamllint version"
      #   run: |
      #     yamllint --version

      - name: "▫️ Lint Yaml"
        run: |
          yamllint ${{ inputs.YAML_DIRS }}
