name: Preview Stackhawk

on:
  workflow_call:
    inputs:
      NAME: # name of service, (ex: peeq-tracking)
        required: true
        type: string
      VERSION:
        required: true
        type: string

jobs:

  preview-stackhawk:
    runs-on: ubuntu-latest
    steps:

      - name: "TODO:"
        run: |
          echo "Preview Stackhawk: ${{ inputs.NAME }} ${{ inputs.VERSION }}"
