name: Repo Get Version

# To use version add to job `needs: get-version`
# Then version is accessible via ${{ needs.++JOB++.outputs.version }} || ${{ needs.get-version.outputs.version }}

on:
  workflow_call:
    secrets:
      GH_TOKEN: # GitHub token
        required: true
    outputs:
      version:
        description: "Repo Version"
        value: ${{ jobs.repo-get-version.outputs.version }}

jobs:

  repo-get-version:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    outputs:
      version: ${{ steps.version.outputs.version  }}
    steps:

      - name: "GITHUB INFO"
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |-
          echo "GITHUB_RUN_ATTEMPT: $GITHUB_RUN_ATTEMPT"
          echo "GITHUB_RUN_ID     : $GITHUB_RUN_ID"
          echo "GITHUB_RUN_NUMBER : $GITHUB_RUN_NUMBER"
          echo "GITHUB_BASE_REF   : $GITHUB_BASE_REF"
          echo "GITHUB_REF_TYPE   : $GITHUB_REF_TYPE"
          echo "GITHUB_REF        : $GITHUB_REF"
          echo "GITHUB_REF_NAME   : $GITHUB_REF_NAME"
          echo "PR number         : ${{ github.event.pull_request.number }}"
          echo "github.event_name : ${{ github.event_name }}"
          echo "--------------------------------------

      - name: "☁️ Checkout repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "☑ Release version"
        id: version
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch
          dry_run: true

      - name: "📜 Display version"
        run: |
          echo "${{ steps.version.outputs.version }}"
