name: Repo Version

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      MONOREPO_APP:
        default: ''
        required: false
        type: string

      INCREMENT_SCRIPT_NAME:
        default: 'auto_increment_version.sh'
        required: false
        type: string

      SCRIPT_GIT_BRANCH:
        default: 'master'
        required: false
        type: string

      SCRIPTS_DOWNLOAD_BASE_URL:
        default: 'https://raw.githubusercontent.com/favedom-dev/github-reusable-workflow'
        required: false
        type: string

      GH_RUNS_ON:
        default: 'ubuntu-latest'
        required: false
        type: string

    secrets:
      GH_TOKEN:
        required: true

    outputs:
      version:
        description: "Repo Version"
        value: ${{ jobs.repo-version.outputs.version }}

      tag:
        description: "Repo Tag"
        value: ${{ jobs.repo-version.outputs.tag }}

      build-version:
        description: "Build Version"
        value: ${{ jobs.repo-version.outputs.build-version }}

jobs:

  repo-version:
    runs-on: ${{ inputs.GH_RUNS_ON }}
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    outputs:
      version: ${{ steps.set-version.outputs.version }}
      tag: ${{ steps.set-version.outputs.tag }}
      build-version: ${{ steps.set-version.outputs.build-version }}
    steps:

      # - name: "📄 GITHUB INFO"
      #   uses: favedom-dev/github-reusable-workflow/.github/actions/debug-github-info@v2
      #   with:
      #     github-context: ${{ toJSON(github) }}
      #     event-name: ${{ github.event_name }}
      #     run-attempt: ${{ github.run_attempt }}
      #     run-number: ${{ github.run_number }}
      #     pr-number: ${{ github.event.pull_request.number }}


      # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
      - name: "📝 Set PR Version"
        id: pr-version
        if: github.event_name == 'pull_request'
        run: |
          pr_number="${{ github.event.number }}"
          pr_run_number="${{ github.run_number }}"
          pr_run_attempt="${{ github.run_attempt }}"
          build-version="${{ github.event.number }}.${{ github.run_number }}.${{ github.run_attempt }}"

          echo "PR Number        (github.event.number) : ${{ github.event.number }}"
          echo "PR Run Number    (github.run_number)   : ${{ github.run_number }}"
          echo "PR Run Attempt   (github.run_attempt)  : ${{ github.run_attempt }}"
          echo "PR Build Version                       : ${build-version}"
          echo "build-version=${build-version}"  >> $GITHUB_OUTPUT
          # echo "build-version=${{ github.event.number }}.${{ github.run_number }}.${{ github.run_attempt }}"  >> $GITHUB_OUTPUT
          echo "version=0.0.0-SNAPSHOT-PR-${{ github.event.number }}-${{ github.run_number }}-${{ github.run_attempt }}"  >> $GITHUB_OUTPUT

      - name: "☁️ Checkout repository"
        uses: actions/checkout@v4
        if: github.event_name != 'pull_request'
        with:
          fetch-depth: 0

      - name: "⬇️ Get reusable files"
        # TODO update to v2
        # uses: favedom-dev/github-reusable-workflow/.github/actions/get-reusable-files@v2
        uses: favedom-dev/github-reusable-workflow/.github/actions/get-reusable-files@FAN-6340
        id: get-reusable-files
        # if: github.event_name != 'pull_request'
        with:
          # FILE_GIT_BRANCH: ${{ inputs.SCRIPT_GIT_BRANCH }}
          # TODO update to v2
          FILE_GIT_BRANCH: FAN-6340
          FILE_DOWNLOAD_BASE_URL: ${{ inputs.SCRIPTS_DOWNLOAD_BASE_URL }}
          FILES_TO_DOWNLOAD: |
            [
              { "subdirectory": "scripts", "filename": "${{ inputs.INCREMENT_SCRIPT_NAME }}" }
            ]

      # - name: "☁️ Get ${{ inputs.INCREMENT_SCRIPT_NAME }}"
      #   if: github.event_name != 'pull_request'
      #   run: |
      #     # wget ${{ inputs.SCRIPTS_DOWNLOAD_BASE_URL }}/${{ inputs.SCRIPT_GIT_BRANCH }}/scripts/${{ inputs.INCREMENT_SCRIPT_NAME }}
      #     curl -o ${{ inputs.INCREMENT_SCRIPT_NAME }} ${{ inputs.SCRIPTS_DOWNLOAD_BASE_URL }}/${{ inputs.SCRIPT_GIT_BRANCH }}/scripts/${{ inputs.INCREMENT_SCRIPT_NAME }}
      #     chmod 777 ./${{ inputs.INCREMENT_SCRIPT_NAME }}

      - name: "☑ Release version"
        id: version
        if: github.event_name != 'pull_request'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          export GH_TOKEN=${{ secrets.GH_TOKEN }}
          export GITHUB_TOKEN=${{ secrets.GH_TOKEN }}
          ./${{ inputs.INCREMENT_SCRIPT_NAME }} ${{ inputs.MONOREPO_APP }}
          VERSION=$(cat VERSION)
          TAG=$(cat TAG)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

      - name: "📝 Set version"
        id: set-version
        env:
          PR_VERSION: ${{ steps.pr-version.outputs.version }}
        run: |
          if [ ${{ env.PR_VERSION }} ]; then
            echo "PR: version   : ${{ steps.pr-version.outputs.version }}"
            echo "PR: build-version: ${{ steps.pr-version.outputs.build-version }}"
            echo "version=${{ steps.pr-version.outputs.version }}" >> $GITHUB_OUTPUT
            echo "build-version=${{ steps.pr-version.outputs.build-version }}" >> $GITHUB_OUTPUT
          else
            echo "RELEASE: version: ${{ steps.version.outputs.version }}"
            echo "version=${{ steps.version.outputs.version }}" >> $GITHUB_OUTPUT
            # TODO: add logic for iOS and Android
            echo "build-version=0.0.0" >> $GITHUB_OUTPUT
          fi
          # echo "${{ steps.version.outputs.version }}"

      - name: "👀 Display version: ${{ steps.set-version.outputs.version }}"
        env:
          PR_VERSION: ${{ steps.pr-version.outputs.version }}
        run: |
          echo "🔖 version            : ${{ steps.set-version.outputs.version }}"

          echo "| Name | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |" >> $GITHUB_STEP_SUMMARY
          echo "| 🔖 Version | \`${{ steps.set-version.outputs.version }}\` |" >> $GITHUB_STEP_SUMMARY

          if [ ${{ env.PR_VERSION }} ]; then
            echo "📦 Build Version (PR) : ${{ steps.set-version.outputs.build-version }}"
            echo "| 📦 PR Version | \`${{ steps.set-version.outputs.build-version }}\` |" >> $GITHUB_STEP_SUMMARY
          else
            echo "🏷️ Tag                : ${{ steps.set-version.outputs.tag }}"
            echo "| 🏷️ Tag | \`${{ steps.set-version.outputs.tag }}\` |" >> $GITHUB_STEP_SUMMARY
          fi
