name: Repo Tag Version

on:  # yamllint disable-line rule:truthy
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:

  repo-get-version:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:

      - name: "☁️ Checkout repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "✅ GitHub release"
        if: ${{ !env.ACT }}
        id: release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch
          tag_prefix: v
