name: Repo Version

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      MONOREPO_APP:
        default: ''
        required: false
        type: string

      INCREMENT_SCRIPT_NAME:
        default: 'auto_increment_version.sh'
        required: false
        type: string

      SCRIPT_GIT_BRANCH:
        default: 'master'
        required: false
        type: string

      SCRIPTS_DOWNLOAD_BASE_URL:
        default: 'https://raw.githubusercontent.com/favedom-dev/github-reusable-workflow'
        required: false
        type: string

      GH_RUNS_ON:
        default: 'ubuntu-latest'
        required: false
        type: string

    secrets:
      GH_TOKEN:
        required: true

    outputs:
      version:
        description: "Repo Version"
        value: ${{ jobs.repo-version.outputs.version }}

      tag:
        description: "Repo Tag"
        value: ${{ jobs.repo-version.outputs.tag }}

      build-version:
        description: "Build Version"
        value: ${{ jobs.repo-version.outputs.build-version }}

jobs:

  repo-version:
    runs-on: ${{ inputs.GH_RUNS_ON }}
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    outputs:
      version: ${{ steps.set-version.outputs.version }}
      tag: ${{ steps.set-version.outputs.tag }}
      build-version: ${{ steps.set-version.outputs.build-version }}
    steps:

      # - name: "📄 GITHUB INFO"
      #   uses: favedom-dev/github-reusable-workflow/.github/actions/debug-github-info@v2
      #   with:
      #     github-context: ${{ toJSON(github) }}
      #     event-name: ${{ github.event_name }}
      #     run-attempt: ${{ github.run_attempt }}
      #     run-number: ${{ github.run_number }}
      #     pr-number: ${{ github.event.pull_request.number }}

      - name: "☁️ Checkout repository"
        uses: actions/checkout@v4
        if: github.event_name != 'pull_request'
        with:
          fetch-depth: 0

      - name: "⬇️ Get reusable files"
        # TODO update to v2
        # uses: favedom-dev/github-reusable-workflow/.github/actions/get-reusable-files@v2
        uses: favedom-dev/github-reusable-workflow/.github/actions/get-reusable-files@FAN-6340
        id: get-reusable-files
        if: github.event_name != 'pull_request'
        with:
          # FILE_GIT_BRANCH: ${{ inputs.SCRIPT_GIT_BRANCH }}
          # TODO update to v2
          FILE_GIT_BRANCH: FAN-6340
          FILE_DOWNLOAD_BASE_URL: ${{ inputs.SCRIPTS_DOWNLOAD_BASE_URL }}
          FILES_TO_DOWNLOAD: |
            [
              { "subdirectory": "scripts", "filename": "${{ inputs.INCREMENT_SCRIPT_NAME }}" }
            ]

      - name: "☑ Release version"
        # TODO update to v2
        # uses: favedom-dev/github-reusable-workflow/.github/actions/set-version-release@v2
        uses: favedom-dev/github-reusable-workflow/.github/actions/set-version-release@FAN-6340
        id: version
        if: github.event_name != 'pull_request'
        with:
          event-name: ${{ github.event_name }}
          increment-script-name: ${{ inputs.INCREMENT_SCRIPT_NAME }}
          monorepo-app: ${{ inputs.MONOREPO_APP }}
          gh-token: ${{ secrets.GH_TOKEN }}

      - name: "📝 Set PR Version"
        # TODO update to v2
        # uses: favedom-dev/github-reusable-workflow/.github/actions/set-version-pr@v2
        uses: favedom-dev/github-reusable-workflow/.github/actions/set-version-pr@FAN-6340
        id: pr-version
        if: github.event_name == 'pull_request'
        with:
          event-name: ${{ github.event_name }}
          pr-number: ${{ github.event.number }}
          run-number: ${{ github.run_number }}
          run-attempt: ${{ github.run_attempt }}

      - name: "📝 Set version"
        # TODO update to v2
        # uses: favedom-dev/github-reusable-workflow/.github/actions/set-version@v2
        uses: favedom-dev/github-reusable-workflow/.github/actions/set-version@FAN-6340
        id: set-version
        with:
          pr-version: ${{ steps.pr-version.outputs.version }}
          pr-build-version: ${{ steps.pr-version.outputs.build-version }}
          release-version: ${{ steps.version.outputs.version }}

      - name: "👀 Display version"
        # TODO update to v2
        # uses: favedom-dev/github-reusable-workflow/.github/actions/set-version-display@v2
        uses: favedom-dev/github-reusable-workflow/.github/actions/set-version-display@FAN-6340
        with:
          version: ${{ steps.set-version.outputs.version }}
          build-version: ${{ steps.set-version.outputs.build-version }}
          tag: ${{ steps.version.outputs.tag }}
          pr-version: ${{ steps.pr-version.outputs.version }}
