name: Repo Version

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      MONOREPO_APP:
        default: ''
        required: false
        type: string

      SIMULATE_PR:
        description: 'Temporarily simulate PR context to bypass non-PR-only logic'
        required: false
        default: false
        type: boolean

      INCREMENT_SCRIPT_NAME:
        default: 'auto_increment_version.sh'
        required: false
        type: string

      SCRIPT_GIT_BRANCH:
        default: 'master'
        required: false
        type: string

      SCRIPTS_DOWNLOAD_BASE_URL:
        default: 'https://raw.githubusercontent.com/favedom-dev/github-reusable-workflow'
        required: false
        type: string

      GH_RUNS_ON:
        default: 'ubuntu-latest'
        required: false
        type: string

    secrets:

      WIF_PROVIDER:
        description: "Workload Identity Federation Provider"
        required: true

      WIF_SERVICE_ACCOUNT:
        description: "Workload Identity Federation Service Account"
        required: true

    #   GH_TOKEN:
    #     required: true

    outputs:
      version:
        description: "Repo Version"
        value: ${{ jobs.repo-version.outputs.version }}

      tag:
        description: "Repo Tag"
        value: ${{ jobs.repo-version.outputs.tag }}

      build-version:
        description: "Build Version"
        value: ${{ jobs.repo-version.outputs.build-version }}

jobs:

  repo-version:
    runs-on: ${{ inputs.GH_RUNS_ON }}
    permissions:
      id-token: write
      contents: read
    # env:
    #   GH_TOKEN: ${{ secrets.GH_TOKEN }}
    #   GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    outputs:
      version: ${{ steps.set-version.outputs.version }}
      tag: ${{ steps.version.outputs.tag }}
      build-version: ${{ steps.set-version.outputs.build-version }}
    steps:

      # - name: "📄 GITHUB INFO"
      #   uses: favedom-dev/github-reusable-workflow/.github/actions/debug-github-info@v2.1
      #   with:
      #     github-context: ${{ toJSON(github) }}
      #     event-name: ${{ github.event_name }}
      #     run-attempt: ${{ github.run_attempt }}
      #     run-number: ${{ github.run_number }}
      #     pr-number: ${{ github.event.pull_request.number }}

      - name: "☁️ Checkout repository"
        uses: actions/checkout@v4
        if: github.event_name != 'pull_request'
        with:
          fetch-depth: 0

      - name: "🔐 Get Secrets"
        uses: favedom-dev/github-reusable-workflow/.github/actions/get-google-secrets@v2.1
        id: get-secrets
        with:
          WIF_PROVIDER: ${{ secrets.WIF_PROVIDER }}
          WIF_SERVICE_ACCOUNT: ${{ secrets.WIF_SERVICE_ACCOUNT }}
          SECRETS_TO_FETCH: "GH_TOKEN:projects/1054075584205/secrets/core_GITHUB_FAVEDOM_DEV_PASSWORD"

      - name: "⬇️ Get reusable files"
        uses: favedom-dev/github-reusable-workflow/.github/actions/get-reusable-files@v2.1
        id: get-reusable-files
        # if: github.event_name != 'pull_request'
        if: github.event_name != 'pull_request' && inputs.SIMULATE_PR == false
        with:
          FILE_GIT_BRANCH: ${{ inputs.SCRIPT_GIT_BRANCH }}
          FILE_DOWNLOAD_BASE_URL: ${{ inputs.SCRIPTS_DOWNLOAD_BASE_URL }}
          FILES_TO_DOWNLOAD: |
            [
              { "subdirectory": "scripts", "filename": "${{ inputs.INCREMENT_SCRIPT_NAME }}" }
            ]

      - name: "☑ Release version"
        uses: favedom-dev/github-reusable-workflow/.github/actions/set-version-release@v2.1
        id: version
        # if: github.event_name != 'pull_request'
        if: github.event_name != 'pull_request' && inputs.SIMULATE_PR == false
        with:
          event-name: ${{ github.event_name }}
          increment-script-name: ${{ inputs.INCREMENT_SCRIPT_NAME }}
          monorepo-app: ${{ inputs.MONOREPO_APP }}
          gh-token: ${{ env.GH_TOKEN }}

      - name: "📝 Set PR Version"
        uses: favedom-dev/github-reusable-workflow/.github/actions/set-version-pr@v2.1
        id: pr-version
        # if: github.event_name == 'pull_request'
        if: github.event_name == 'pull_request' || inputs.SIMULATE_PR == true
        with:
          event-name: ${{ github.event_name }}
          pr-number: ${{ github.event.number }}
          run-number: ${{ github.run_number }}
          run-attempt: ${{ github.run_attempt }}

      - name: "📝 Set version"
        uses: favedom-dev/github-reusable-workflow/.github/actions/set-version@v2.1
        id: set-version
        with:
          pr-version: ${{ steps.pr-version.outputs.version }}
          pr-build-version: ${{ steps.pr-version.outputs.build-version }}
          release-version: ${{ steps.version.outputs.version }}

      - name: "👀 Display version"
        uses: favedom-dev/github-reusable-workflow/.github/actions/set-version-display@v2.1
        with:
          version: ${{ steps.set-version.outputs.version }}
          build-version: ${{ steps.set-version.outputs.build-version }}
          tag: ${{ steps.version.outputs.tag }}
          pr-version: ${{ steps.pr-version.outputs.version }}
          # monorepo-app: ${{ inputs.MONOREPO_APP }}
