name: Repo Tag
run-name: "Repo Tag: ${{ inputs.TAG_NAME }} Branch: ${{ inputs.BRANCH_NAME }}"

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      TAG_NAME:
        default: v2
        description: "Git tag name"
        required: true
        type: string
      BRANCH_NAME:
        # default: master
        default: v2-base
        description: "Git branch name"
        required: true
        type: string

jobs:

  git-tag:
    uses: favedom-dev/github-reusable-workflow/.github/workflows/repo-update-tag.yaml@master
    with:
      TAG_NAME: ${{ inputs.TAG_NAME }}
      BRANCH_NAME: ${{ inputs.BRANCH_NAME }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
