name: Set App Name

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      OVERRIDE_NAME:
        required: false
        type: string
    outputs:
      NAME:
        value: ${{ jobs.app-name.outputs.NAME  }}

jobs:

  set-app-name:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    outputs:
      NAME: ${{ steps.set-name.outputs.NAME  }}
    steps:

      - name: "Set Name"
        id: set-name
        env:
          OVERRIDE_NAME: ${{ inputs.OVERRIDE_NAME }}
        run: |
          NAME=${{ github.event.repository.name }}
          echo "OVERRIDE_NAME: ${OVERRIDE_NAME}"
          if [ -n "${OVERRIDE_NAME}" ]; then
            NAME=${{ inputs.OVERRIDE_NAME }}
          fi
          echo "::set-output name=NAME::${NAME}"
