name: App Setup

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      OVERRIDE_NAME:
        required: false
        type: string

      OVERRIDE_PREVIEW_NAMESPACE:
        required: false
        type: string

      USE_REPO_NAME_PREVIEW_NAMESPACE:
        default: false
        required: false
        type: boolean

      IS_STACKHAWK_READY:
        default: true
        required: false
        type: boolean

      OVERRIDE_IS_STACKHAWK_READY:
        required: false
        type: string

      STACKHAWK_DIRECTORY:
        default: 'stackhawk'
        required: false
        type: string

      STACKHAWK_TMPL_YML:
        default: 'stackhawk-tmpl.yml'
        required: false
        type: string

      DO_TRIVY:
        required: false
        type: string

      IS_FRONTEND:
        default: false
        required: false
        type: boolean

      IS_MONOREPO:
        default: false
        required: false
        type: boolean

      GH_RUNS_ON:
        default: 'ubuntu-latest'
        # default: 'core'
        required: false
        type: string

    outputs:
      NAME:
        value: ${{ jobs.app-setup.outputs.NAME }}
        description: "App/Service name"

      PREVIEW_NAMESPACE:
        value: ${{ jobs.app-setup.outputs.PREVIEW_NAMESPACE }}

      IS_STACKHAWK_READY:
        value: ${{ jobs.app-setup.outputs.IS_STACKHAWK_READY }}

      STACKHAWK_DIRECTORY:
        value: ${{ jobs.app-setup.outputs.STACKHAWK_DIRECTORY }}

      DO_TRIVY:
        value: ${{ jobs.app-setup.outputs.DO_TRIVY }}

jobs:

  app-setup:
    timeout-minutes: 1
    runs-on: ${{ inputs.GH_RUNS_ON }}
    outputs:
      NAME: ${{ steps.set-name.outputs.NAME }}
      PREVIEW_NAMESPACE: ${{ steps.set-name-pr-namespace.outputs.PREVIEW_NAMESPACE }}
      IS_STACKHAWK_READY: ${{ steps.stackhawk-ready-repo.outputs.IS_STACKHAWK_READY }}
      STACKHAWK_DIRECTORY: ${{ steps.stackhawk-ready-repo.outputs.STACKHAWK_DIRECTORY }}
      DO_TRIVY: ${{ steps.setup-security-trivy.outputs.DO_TRIVY }}
      IS_FRONTEND: ${{ steps.extra-vars.outputs.IS_FRONTEND }}
      IS_MONOREPO: ${{ steps.extra-vars.outputs.IS_MONOREPO }}
    steps:

      - name: "📝 Set Name"
        uses: favedom-dev/github-reusable-workflow/.github/actions/setup-set-name@v2
        id: set-name
        with:
          override-name: ${{ inputs.OVERRIDE_NAME }}
          repo-name: ${{ github.event.repository.name }}

      - name: "📝 Set Extra Vars"
        uses: favedom-dev/github-reusable-workflow/.github/actions/setup-set-extra-vars@v2
        id: extra-vars
        with:
          is-frontend: ${{ inputs.IS_FRONTEND }}
          is-monorepo: ${{ inputs.IS_MONOREPO }}

      - name: "📝 Set Preview Namespace name"
        uses: favedom-dev/github-reusable-workflow/.github/actions/setup-set-preview-namespace@v2
        id: set-name-pr-namespace
        with:
          override-preview-namespace: ${{ inputs.OVERRIDE_PREVIEW_NAMESPACE }}
          use-repo-name-preview-namespace: ${{ inputs.USE_REPO_NAME_PREVIEW_NAMESPACE }}
          repo-full-name: ${{ github.repository }}
          event-number: ${{ github.event.number }}
          name: ${{ steps.set-name.outputs.NAME }}

      - name: "☁️ Checkout repository"
        uses: actions/checkout@v4

      - name: "🦅 Stackhawk ready repo"
        uses: favedom-dev/github-reusable-workflow/.github/actions/setup-stackhawk-ready-repo@v2
        id: stackhawk-ready-repo
        with:
          stackhawk-directory: ${{ inputs.STACKHAWK_DIRECTORY }}
          stackhawk-tmpl-yml: ${{ inputs.STACKHAWK_TMPL_YML }}
          is-stackhawk-ready: ${{ inputs.IS_STACKHAWK_READY }}
          override-is-stackhawk-ready: ${{ inputs.OVERRIDE_IS_STACKHAWK_READY }}

      - name: "🛡️ Setup Trivy"
        # TODO
        # uses: favedom-dev/github-reusable-workflow/.github/actions/setup-security-trivy@v2
        uses: favedom-dev/github-reusable-workflow/.github/actions/setup-security-trivy@FAN-6956-secrets
        id: setup-security-trivy
        with:
          DO_TRIVY: ${{ inputs.DO_TRIVY }}


      - name: "👀 Display values: ${{ steps.set-name.outputs.NAME }} "
        run: |
          echo "NAME                : ${{ steps.set-name.outputs.NAME }}"
          echo "PREVIEW_NAMESPACE   : ${{ steps.set-name-pr-namespace.outputs.PREVIEW_NAMESPACE }}"
          echo "IS_STACKHAWK_READY  : ${{ steps.stackhawk-ready-repo.outputs.IS_STACKHAWK_READY }}"
          echo "STACKHAWK_DIRECTORY : ${{ steps.stackhawk-ready-repo.outputs.STACKHAWK_DIRECTORY }}"
          echo "DO_TRIVY            : ${{ steps.setup-security-trivy.outputs.DO_TRIVY }}"
          echo "IS_FRONTEND         : ${{ steps.extra-vars.outputs.IS_FRONTEND }}"
          echo "IS_MONOREPO         : ${{ steps.extra-vars.outputs.IS_MONOREPO }}"
          #
          # echo "## App Values" >> $GITHUB_STEP_SUMMARY
          echo "| Property            | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| ---                 | --- |" >> $GITHUB_STEP_SUMMARY
          echo "| NAME                | \`${{ steps.set-name.outputs.NAME }}\` |" >> $GITHUB_STEP_SUMMARY
          echo "| PREVIEW_NAMESPACE   | \`${{ steps.set-name-pr-namespace.outputs.PREVIEW_NAMESPACE }}\` |" >> $GITHUB_STEP_SUMMARY
          echo "| IS_STACKHAWK_READY  | \`${{ steps.stackhawk-ready-repo.outputs.IS_STACKHAWK_READY }}\` |" >> $GITHUB_STEP_SUMMARY
          echo "| STACKHAWK_DIRECTORY | \`${{ steps.stackhawk-ready-repo.outputs.STACKHAWK_DIRECTORY }}\` |" >> $GITHUB_STEP_SUMMARY
          echo "| DO_TRIVY            | \`${{ steps.setup-security-trivy.outputs.DO_TRIVY }}\` |" >> $GITHUB_STEP_SUMMARY
          echo "| IS_FRONTEND         | \`${{ steps.extra-vars.outputs.IS_FRONTEND }}\` |" >> $GITHUB_STEP_SUMMARY
          echo "| IS_MONOREPO         | \`${{ steps.extra-vars.outputs.IS_MONOREPO }}\` |" >> $GITHUB_STEP_SUMMARY

