name: setup-get-secrets

on:
  workflow_call:

    inputs:
      secrets-to-fetch:
        description: 'Comma-separated list of secret names to retrieve from Google Cloud Secret Manager (format: secret-name|output-key)'
        required: true
        type: string
      # project-id:
      #   description: 'Google Cloud Project ID where secrets are stored'
      #   required: true
      #   type: string

    secrets:
      WIF_PROVIDER:
        description: "Workload Identity Federation Provider"
        required: true

      WIF_SERVICE_ACCOUNT:
        description: "Workload Identity Federation Service Account"
        required: true

    outputs:
      secrets:
        description: 'JSON object containing fetched secrets'
        value: ${{ jobs.get-secrets.outputs.secrets }}

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    outputs:
      secrets: ${{ steps.set-secrets.outputs.secrets }}

    steps:

      - name: "🔑 Google Auth Token"
        id: auth-gcp-token
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      - name: "🤫 Get Secrets"
        id: get-secrets
        uses: google-github-actions/get-secretmanager-secrets@v2
        with:
          secrets: ${{ inputs.secrets-to-fetch }}

      - name: "🕵️‍♂️ Set Secrets as Outputs"
        id: set-secrets
        run: |
          secrets_json=$(jq -n '{}')
          echo "inputs.secrets-to-fetch : ${{ inputs.secrets-to-fetch }}"
          IFS=',' read -ra SECRETS <<< "${{ inputs.secrets-to-fetch }}"
          for secret in "${SECRETS[@]}"; do
            secret_name=$(echo "$secret" | cut -d'|' -f1)
            echo "secret_name : ${secret_name}"

            secret_key=$(echo "$secret" | cut -d'|' -f2)
            echo "secret_key  : ${secret_key}"

            secret_value=${{ steps.get-secrets.outputs[$secret_key] }}
            # echo "secret_value  : ${secret_value}"

            echo "Mask secret_value..."
            echo "::add-mask::$secret_value"
            secrets_json=$(echo "$secrets_json" | jq --arg key "$secret_key" --arg value "$secret_value" '. += {($key): $value}')
          done
          echo "secrets_json :"
          echo "${secrets_json}" | jq .
          echo "secrets=$secrets_json" >> $GITHUB_OUTPUT
